# DAY 26 : ADVANCED PANDAS I

In [2]:
import pandas as pd

In [3]:
# Orders
orders = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104],
    "Customer_ID": ["C01", "C02", "C01", "C04"],
    "Sales": [500, 700, 300, 900]
})

orders

   Order_ID Customer_ID  Sales
0       101         C01    500
1       102         C02    700
2       103         C01    300
3       104         C04    900

In [4]:
# Customers
customers = pd.DataFrame({
    "Customer_ID": ["C01", "C02", "C03"],
    "Customer_Name": ["Rahul", "Amit", "Sneha"],
    "Segment": ["Consumer", "Corporate", "Consumer"]
})

customers

  Customer_ID Customer_Name    Segment
0         C01         Rahul   Consumer
1         C02          Amit  Corporate
2         C03         Sneha   Consumer

In [5]:
# merge()
merged_data = pd.merge(
     orders , customers , on="Customer_ID"
)
merged_data

   Order_ID Customer_ID  Sales Customer_Name    Segment
0       101         C01    500         Rahul   Consumer
1       102         C02    700          Amit  Corporate
2       103         C01    300         Rahul   Consumer

In [10]:
# Inner Join
pd.merge(
     orders , customers , on="Customer_ID" , how="inner"
).shape

(3, 5)

In [11]:
# Outer Join
pd.merge(
     orders , customers , on="Customer_ID" , how="outer"
).shape

(5, 5)

In [12]:
# Left join
pd.merge(
     orders , customers , on="Customer_ID" , how="left"
).shape

(4, 5)

In [13]:
# Right Join
pd.merge(
     orders , customers , on="Customer_ID" , how="right"
).shape

(4, 5)

### Vertical concat()

In [15]:
# Create two monthly datasets
# January Sales
sales_jan = pd.DataFrame({
    "Order_ID": [101, 102],
    "Sales": [500, 700]
})

In [16]:
# February Sales
sales_feb = pd.DataFrame({
    "Order_ID": [103, 104],
    "Sales": [300, 900]
})

In [18]:
sales = pd.concat(
     [sales_jan , sales_feb],
     ignore_index=True
)
sales

   Order_ID  Sales
0       101    500
1       102    700
2       103    300
3       104    900

In [19]:
sales.shape

(4, 2)

### Horizontal concat()

In [20]:
# create another DataFrame
customer_info = pd.DataFrame({
    "Customer_ID": ["C01", "C02", "C01", "C04"],
    "Segment": ["Consumer", "Corporate", "Consumer", "Home Office"]
})

In [21]:
sales_with_customer = pd.concat(
    [sales, customer_info],
    axis=1
)

sales_with_customer

   Order_ID  Sales Customer_ID      Segment
0       101    500         C01     Consumer
1       102    700         C02    Corporate
2       103    300         C01     Consumer
3       104    900         C04  Home Office

In [22]:
sales_with_customer.shape

(4, 4)

### join()

In [25]:
orders_indexed = orders.set_index("Customer_ID")
customers_indexed = customers.set_index("Customer_ID")

orders_indexed

             Order_ID  Sales
Customer_ID
C01               101    500
C02               102    700
C01               103    300
C04               104    900

In [26]:
customers_indexed

            Customer_Name    Segment
Customer_ID
C01                 Rahul   Consumer
C02                  Amit  Corporate
C03                 Sneha   Consumer

In [39]:
# Perform left join
joined_data = orders_indexed.join(
     customers_indexed ,
     how= "left"
)
joined_data

             Order_ID  Sales Customer_Name    Segment
Customer_ID
C01               101    500         Rahul   Consumer
C02               102    700          Amit  Corporate
C01               103    300         Rahul   Consumer
C04               104    900           NaN        NaN

In [30]:
joined_data.shape

(4, 4)

### BUSINESS SCENARIOS

In [35]:
customer_sales = merged_data.groupby(
     "Segment"
).agg(
     Total_sales = ("Sales" , "sum"),
     Total_orders = ("Order_ID" , "nunique")
)
customer_sales

           Total_sales  Total_orders
Segment
Consumer           800             2
Corporate          700             1

In [38]:
     # calculate each segment
customer_sales["Sales_Contribution_%"] = (
    customer_sales["Total_sales"]
     .div(customer_sales["Total_sales"].sum())
     .mul(100)
)
customer_sales

           Total_sales  Total_orders  Sales_Contribution_%
Segment
Consumer           800             2             53.333333
Corporate          700             1             46.666667