PIVOT TABLES AND CROSS TAB BUSINESS ANALLYSIS

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" , encoding="latin1")
df.head()

,Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,shipping date (DateOrders),Shipping Mode
0,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,...,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,Smart watch,02-03-2018 22:56,Standard Class
1,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,...,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,Smart watch,1/18/2018 12:27,Standard Class
2,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,...,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,Smart watch,1/17/2018 12:06,Standard Class
3,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,...,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,Smart watch,1/16/2018 11:45,Standard Class
4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,...,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,Smart watch,1/15/2018 11:24,Standard Class

PIVOT TABLE

In [7]:
# how much sales does each customer segment generate in each market.
market_segment_pivot = pd.pivot_table(
     df ,
     values="Sales" ,
     index= "Market",
     columns="Customer Segment" ,
     aggfunc="sum")
market_segment_pivot

Customer Segment      Consumer     Corporate   Home Office
Market
Africa            1.187434e+06  6.997575e+05  4.072613e+05
Europe            5.671565e+06  3.303071e+06  1.897761e+06
LATAM             5.289639e+06  3.139115e+06  1.848859e+06
Pacific Asia      4.286861e+06  2.515593e+06  1.471290e+06
USCA              2.660291e+06  1.510871e+06  8.953663e+05

In [8]:
# for every market and customer segment ,  show me both profit and sales
market_segment_pivot = pd.pivot_table(
     df ,
     values=["Sales" , "Order Profit Per Order"] ,
     index= "Market",
     columns="Customer Segment" ,
     aggfunc="sum")
market_segment_pivot

                 Order Profit Per Order                                \
Customer Segment               Consumer      Corporate    Home Office
Market
Africa                    129600.889959   75761.369980   46708.920134
Europe                    627099.000311  355412.120425  186931.840263
LATAM                     568246.210506  350573.820505  204501.580481
Pacific Asia              445629.430767  258109.510353  154014.499987
USCA                      302912.140371  162718.140245   98683.499766

                         Sales
Customer Segment      Consumer     Corporate   Home Office
Market
Africa            1.187434e+06  6.997575e+05  4.072613e+05
Europe            5.671565e+06  3.303071e+06  1.897761e+06
LATAM             5.289639e+06  3.139115e+06  1.848859e+06
Pacific Asia      4.286861e+06  2.515593e+06  1.471290e+06
USCA              2.660291e+06  1.510871e+06  8.953663e+05

In [9]:
# waht is total sales for each market , regardless of customer segment
sales_pivot = pd.pivot_table(
     df ,
     values="Sales" ,
     index="Market" ,
     columns="Customer Segment" ,
     aggfunc="sum" ,
     margins=True
)
sales_pivot

Customer Segment      Consumer     Corporate   Home Office           All
Market
Africa            1.187434e+06  6.997575e+05  4.072613e+05  2.294453e+06
Europe            5.671565e+06  3.303071e+06  1.897761e+06  1.087240e+07
LATAM             5.289639e+06  3.139115e+06  1.848859e+06  1.027761e+07
Pacific Asia      4.286861e+06  2.515593e+06  1.471290e+06  8.273744e+06
USCA              2.660291e+06  1.510871e+06  8.953663e+05  5.066529e+06
All               1.909579e+07  1.116841e+07  6.520538e+06  3.678474e+07

CROSS TABULATION

In [10]:
# Cross Tabulation
market_segment_count = pd.crosstab(
     df["Market"] , 
     df["Customer Segment"]
)
market_segment_count

Customer Segment  Consumer  Corporate  Home Office
Market
Africa                6007       3528         2079
Europe               26108      15313         8831
LATAM                26598      15699         9297
Pacific Asia         21284      12508         7468
USCA                 13507       7741         4551

In [11]:
     # add grand total to crosstab
market_segment_count = pd.crosstab(
     df["Market"] ,
     df["Customer Segment"],
     margins=True
)
market_segment_count

Customer Segment  Consumer  Corporate  Home Office     All
Market
Africa                6007       3528         2079   11614
Europe               26108      15313         8831   50252
LATAM                26598      15699         9297   51594
Pacific Asia         21284      12508         7468   41260
USCA                 13507       7741         4551   25799
All                  93504      54789        32226  180519