FIRST MINI PROJECT : EMPLOYEE DATA ANALYSIS

In [1]:
import pandas as pd

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_18996\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
employee_df = pd.read_csv("employee_data.csv")

employee_df

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance_Rating
0,E001,Rahul Sharma,Sales,Pune,2,48000,4
1,E002,Priya Patel,HR,Mumbai,5,65000,5
2,E003,Amit Verma,IT,Bangalore,4,72000,4
3,E004,Sneha Joshi,Finance,Pune,3,58000,3
4,E005,Rohan Singh,IT,Delhi,6,81000,5
5,E006,Anjali Mehta,HR,Ahmedabad,2,52000,4
6,E007,Vikram Rao,Sales,Hyderabad,7,85000,5
7,E008,Neha Gupta,Marketing,Pune,4,61000,4
8,E009,Karan Shah,Finance,Mumbai,5,69000,4
9,E010,Pooja Iyer,IT,Chennai,1,45000,3
10,E011,Rahul Sharma,Sales,Pune,2,48000,4
11,E012,Priya Patel,HR,Mumbai,5,65000,5
12,E013,Arjun Nair,IT,Kochi,3,60000,4
13,E014,Meera Kulkarni,Finance,Nagpur,8,92000,5
14,E015,Sachin Deshmukh,Sales,Pune,4,62000,4
15,E016,Divya Reddy,Marketing,Hyderabad,6,78000,5
16,E017,Nikhil Jain,IT,Jaipur,2,54000,3
17,E018,Ritu Kapoor,HR,Delhi,7,88000,5
18,E019,Akash Patil,Finance,Pune,5,71000,4
19,E020,Simran Kaur,Marketing,Chandigarh,3,59000,4

In [3]:
employee_df.head(5)

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance_Rating
0,E001,Rahul Sharma,Sales,Pune,2,48000,4
1,E002,Priya Patel,HR,Mumbai,5,65000,5
2,E003,Amit Verma,IT,Bangalore,4,72000,4
3,E004,Sneha Joshi,Finance,Pune,3,58000,3
4,E005,Rohan Singh,IT,Delhi,6,81000,5

In [4]:
employee_df.tail(5)

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance_Rating
15,E016,Divya Reddy,Marketing,Hyderabad,6,78000,5
16,E017,Nikhil Jain,IT,Jaipur,2,54000,3
17,E018,Ritu Kapoor,HR,Delhi,7,88000,5
18,E019,Akash Patil,Finance,Pune,5,71000,4
19,E020,Simran Kaur,Marketing,Chandigarh,3,59000,4

In [5]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         20 non-null     object
 1   Employee_Name       20 non-null     object
 2   Department          20 non-null     object
 3   City                20 non-null     object
 4   Experience          20 non-null     int64
 5   Salary              20 non-null     int64
 6   Performance_Rating  20 non-null     int64
dtypes: int64(3), object(4)
memory usage: 1.2+ KB

In [6]:
employee_df.describe()

       Experience        Salary  Performance_Rating
count   20.000000     20.000000           20.000000
mean     4.200000  65650.000000            4.200000
std      1.962812  13723.874702            0.695852
min      1.000000  45000.000000            3.000000
25%      2.750000  57000.000000            4.000000
50%      4.000000  63500.000000            4.000000
75%      5.250000  73500.000000            5.000000
max      8.000000  92000.000000            5.000000

In [7]:
employee_df.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'City', 'Experience',
       'Salary', 'Performance_Rating'],
      dtype='object')

In [8]:
employee_df.shape

(20, 7)

In [9]:
employee_df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [10]:
employee_df.duplicated().sum()

0

In [12]:
employee_df[
     employee_df.duplicated()
]

Empty DataFrame
Columns: [Employee_ID, Employee_Name, Department, City, Experience, Salary, Performance_Rating]
Index: []

In [14]:
clean_df = employee_df.drop_duplicates()
clean_df

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance_Rating
0,E001,Rahul Sharma,Sales,Pune,2,48000,4
1,E002,Priya Patel,HR,Mumbai,5,65000,5
2,E003,Amit Verma,IT,Bangalore,4,72000,4
3,E004,Sneha Joshi,Finance,Pune,3,58000,3
4,E005,Rohan Singh,IT,Delhi,6,81000,5
5,E006,Anjali Mehta,HR,Ahmedabad,2,52000,4
6,E007,Vikram Rao,Sales,Hyderabad,7,85000,5
7,E008,Neha Gupta,Marketing,Pune,4,61000,4
8,E009,Karan Shah,Finance,Mumbai,5,69000,4
9,E010,Pooja Iyer,IT,Chennai,1,45000,3
10,E011,Rahul Sharma,Sales,Pune,2,48000,4
11,E012,Priya Patel,HR,Mumbai,5,65000,5
12,E013,Arjun Nair,IT,Kochi,3,60000,4
13,E014,Meera Kulkarni,Finance,Nagpur,8,92000,5
14,E015,Sachin Deshmukh,Sales,Pune,4,62000,4
15,E016,Divya Reddy,Marketing,Hyderabad,6,78000,5
16,E017,Nikhil Jain,IT,Jaipur,2,54000,3
17,E018,Ritu Kapoor,HR,Delhi,7,88000,5
18,E019,Akash Patil,Finance,Pune,5,71000,4
19,E020,Simran Kaur,Marketing,Chandigarh,3,59000,4

In [15]:
clean_df.shape

(20, 7)

In [ ]:
employee_df.drop_duplicates(
     subset=["Employee_Name"]
)

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance_Rating
0,E001,Rahul Sharma,Sales,Pune,2,48000,4
1,E002,Priya Patel,HR,Mumbai,5,65000,5
2,E003,Amit Verma,IT,Bangalore,4,72000,4
3,E004,Sneha Joshi,Finance,Pune,3,58000,3
4,E005,Rohan Singh,IT,Delhi,6,81000,5
5,E006,Anjali Mehta,HR,Ahmedabad,2,52000,4
6,E007,Vikram Rao,Sales,Hyderabad,7,85000,5
7,E008,Neha Gupta,Marketing,Pune,4,61000,4
8,E009,Karan Shah,Finance,Mumbai,5,69000,4
9,E010,Pooja Iyer,IT,Chennai,1,45000,3
12,E013,Arjun Nair,IT,Kochi,3,60000,4
13,E014,Meera Kulkarni,Finance,Nagpur,8,92000,5
14,E015,Sachin Deshmukh,Sales,Pune,4,62000,4
15,E016,Divya Reddy,Marketing,Hyderabad,6,78000,5
16,E017,Nikhil Jain,IT,Jaipur,2,54000,3
17,E018,Ritu Kapoor,HR,Delhi,7,88000,5
18,E019,Akash Patil,Finance,Pune,5,71000,4
19,E020,Simran Kaur,Marketing,Chandigarh,3,59000,4

In [18]:
employee_df.drop_duplicates(
     subset=["Employee_Name"]
).shape

(18, 7)

In [19]:
employee_df.drop_duplicates(
     subset=["Employee_Name"]
).duplicated(
     subset=["Employee_Name"]
).sum()

0

In [20]:
employee_df[
     employee_df["Salary"] > 70000
]

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance_Rating
2,E003,Amit Verma,IT,Bangalore,4,72000,4
4,E005,Rohan Singh,IT,Delhi,6,81000,5
6,E007,Vikram Rao,Sales,Hyderabad,7,85000,5
13,E014,Meera Kulkarni,Finance,Nagpur,8,92000,5
15,E016,Divya Reddy,Marketing,Hyderabad,6,78000,5
17,E018,Ritu Kapoor,HR,Delhi,7,88000,5
18,E019,Akash Patil,Finance,Pune,5,71000,4

In [21]:
employee_df[
     employee_df["Department"] == "IT"
]

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance_Rating
2,E003,Amit Verma,IT,Bangalore,4,72000,4
4,E005,Rohan Singh,IT,Delhi,6,81000,5
9,E010,Pooja Iyer,IT,Chennai,1,45000,3
12,E013,Arjun Nair,IT,Kochi,3,60000,4
16,E017,Nikhil Jain,IT,Jaipur,2,54000,3

In [22]:
employee_df[
     employee_df["Experience"] >= 5
]

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance_Rating
1,E002,Priya Patel,HR,Mumbai,5,65000,5
4,E005,Rohan Singh,IT,Delhi,6,81000,5
6,E007,Vikram Rao,Sales,Hyderabad,7,85000,5
8,E009,Karan Shah,Finance,Mumbai,5,69000,4
11,E012,Priya Patel,HR,Mumbai,5,65000,5
13,E014,Meera Kulkarni,Finance,Nagpur,8,92000,5
15,E016,Divya Reddy,Marketing,Hyderabad,6,78000,5
17,E018,Ritu Kapoor,HR,Delhi,7,88000,5
18,E019,Akash Patil,Finance,Pune,5,71000,4

In [23]:
employee_df.sort_values(
     ["Salary"] , 
     ascending=False
)

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance_Rating
13,E014,Meera Kulkarni,Finance,Nagpur,8,92000,5
17,E018,Ritu Kapoor,HR,Delhi,7,88000,5
6,E007,Vikram Rao,Sales,Hyderabad,7,85000,5
4,E005,Rohan Singh,IT,Delhi,6,81000,5
15,E016,Divya Reddy,Marketing,Hyderabad,6,78000,5
2,E003,Amit Verma,IT,Bangalore,4,72000,4
18,E019,Akash Patil,Finance,Pune,5,71000,4
8,E009,Karan Shah,Finance,Mumbai,5,69000,4
1,E002,Priya Patel,HR,Mumbai,5,65000,5
11,E012,Priya Patel,HR,Mumbai,5,65000,5
14,E015,Sachin Deshmukh,Sales,Pune,4,62000,4
7,E008,Neha Gupta,Marketing,Pune,4,61000,4
12,E013,Arjun Nair,IT,Kochi,3,60000,4
19,E020,Simran Kaur,Marketing,Chandigarh,3,59000,4
3,E004,Sneha Joshi,Finance,Pune,3,58000,3
16,E017,Nikhil Jain,IT,Jaipur,2,54000,3
5,E006,Anjali Mehta,HR,Ahmedabad,2,52000,4
0,E001,Rahul Sharma,Sales,Pune,2,48000,4
10,E011,Rahul Sharma,Sales,Pune,2,48000,4
9,E010,Pooja Iyer,IT,Chennai,1,45000,3

In [28]:
report_df = employee_df.rename(
     columns={
     "Performance_Rating" : "Performance Score"
     }
)
report_df

,Employee_ID,Employee_Name,Department,City,Experience,Salary,Performance Score
0,E001,Rahul Sharma,Sales,Pune,2,48000,4
1,E002,Priya Patel,HR,Mumbai,5,65000,5
2,E003,Amit Verma,IT,Bangalore,4,72000,4
3,E004,Sneha Joshi,Finance,Pune,3,58000,3
4,E005,Rohan Singh,IT,Delhi,6,81000,5
5,E006,Anjali Mehta,HR,Ahmedabad,2,52000,4
6,E007,Vikram Rao,Sales,Hyderabad,7,85000,5
7,E008,Neha Gupta,Marketing,Pune,4,61000,4
8,E009,Karan Shah,Finance,Mumbai,5,69000,4
9,E010,Pooja Iyer,IT,Chennai,1,45000,3
10,E011,Rahul Sharma,Sales,Pune,2,48000,4
11,E012,Priya Patel,HR,Mumbai,5,65000,5
12,E013,Arjun Nair,IT,Kochi,3,60000,4
13,E014,Meera Kulkarni,Finance,Nagpur,8,92000,5
14,E015,Sachin Deshmukh,Sales,Pune,4,62000,4
15,E016,Divya Reddy,Marketing,Hyderabad,6,78000,5
16,E017,Nikhil Jain,IT,Jaipur,2,54000,3
17,E018,Ritu Kapoor,HR,Delhi,7,88000,5
18,E019,Akash Patil,Finance,Pune,5,71000,4
19,E020,Simran Kaur,Marketing,Chandigarh,3,59000,4

In [31]:
employee_df.loc[
     : ,
     ["Employee_Name" , "Department" , "Salary"]
     ]

      Employee_Name Department  Salary
0      Rahul Sharma      Sales   48000
1       Priya Patel         HR   65000
2        Amit Verma         IT   72000
3       Sneha Joshi    Finance   58000
4       Rohan Singh         IT   81000
5      Anjali Mehta         HR   52000
6        Vikram Rao      Sales   85000
7        Neha Gupta  Marketing   61000
8        Karan Shah    Finance   69000
9        Pooja Iyer         IT   45000
10     Rahul Sharma      Sales   48000
11      Priya Patel         HR   65000
12       Arjun Nair         IT   60000
13   Meera Kulkarni    Finance   92000
14  Sachin Deshmukh      Sales   62000
15      Divya Reddy  Marketing   78000
16      Nikhil Jain         IT   54000
17      Ritu Kapoor         HR   88000
18      Akash Patil    Finance   71000
19      Simran Kaur  Marketing   59000

In [40]:
employee_df.iloc[
    0:10 , 
     [1]
]

  Employee_Name
0  Rahul Sharma
1   Priya Patel
2    Amit Verma
3   Sneha Joshi
4   Rohan Singh
5  Anjali Mehta
6    Vikram Rao
7    Neha Gupta
8    Karan Shah
9    Pooja Iyer