PIVOT TABLE AND CROSSTAB

In [1]:
import pandas as pd

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_2736\2035458946.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
employee_data = {
    "Employee": [
        "Rahul","Priya","Amit","Sneha",
        "Rohan","Neha","Karan","Pooja"
    ],
    "Department": [
        "Sales","HR","IT","Finance",
        "IT","Sales","HR","Finance"
    ],
    "City": [
        "Pune","Mumbai","Pune","Delhi",
        "Mumbai","Pune","Delhi","Mumbai"
    ],
    "Salary": [
        50000,65000,70000,55000,
        80000,62000,68000,72000
    ]
}

employee_df = pd.DataFrame(employee_data)

employee_df

  Employee Department    City  Salary
0    Rahul      Sales    Pune   50000
1    Priya         HR  Mumbai   65000
2     Amit         IT    Pune   70000
3    Sneha    Finance   Delhi   55000
4    Rohan         IT  Mumbai   80000
5     Neha      Sales    Pune   62000
6    Karan         HR   Delhi   68000
7    Pooja    Finance  Mumbai   72000

PIVOT_TABLE()

In [ ]:
# average salary by department
employee_df.pivot_table(
     values="Salary",
     index="Department",
     aggfunc="mean"
)

             Salary
Department
Finance     63500.0
HR          66500.0
IT          75000.0
Sales       56000.0

In [4]:
# total salary by department
employee_df.pivot_table(
     values="Salary",
     index="Department",
     aggfunc="sum"
)

            Salary
Department
Finance     127000
HR          133000
IT          150000
Sales       112000

MULTIPLE AGGREGATIONS

In [9]:
employee_df.pivot_table(
     values="Salary",
     index="Department",
     aggfunc=["mean" , "sum" , "min" , "max" , "count"]
)

               mean     sum    min    max  count
             Salary  Salary Salary Salary Salary
Department
Finance     63500.0  127000  55000  72000      2
HR          66500.0  133000  65000  68000      2
IT          75000.0  150000  70000  80000      2
Sales       56000.0  112000  50000  62000      2

MULTIPLE INDEX

In [10]:
employee_df.pivot_table(
     values="Salary",
     index=["Department" , "City"],
     aggfunc="mean"
)

                    Salary
Department City
Finance    Delhi   55000.0
           Mumbai  72000.0
HR         Delhi   68000.0
           Mumbai  65000.0
IT         Mumbai  80000.0
           Pune    70000.0
Sales      Pune    56000.0

PIVOT()

In [11]:
sales_df = pd.DataFrame({
    "Month": ["Jan", "Jan", "Feb", "Feb"],
    "Product": ["Laptop", "Mouse", "Laptop", "Mouse"],
    "Sales": [50000, 8000, 60000, 9000]
})

sales_df

  Month Product  Sales
0   Jan  Laptop  50000
1   Jan   Mouse   8000
2   Feb  Laptop  60000
3   Feb   Mouse   9000

In [13]:
sales_df.pivot(
     columns="Product",
     index="Month",
     values="Sales"
)

Product  Laptop  Mouse
Month
Feb       60000   9000
Jan       50000   8000

CROSSTAB()

In [14]:
pd.crosstab(
     employee_df["Department"],
     employee_df["City"]
)

City        Delhi  Mumbai  Pune
Department
Finance         1       1     0
HR              1       1     0
IT              0       1     1
Sales           0       0     2