ADVANCED DATA ANALYSIS WITH PANDAS

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" ,
                 encoding="latin1")
df.head()

,Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,shipping date (DateOrders),Shipping Mode
0,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,...,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,Smart watch,02-03-2018 22:56,Standard Class
1,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,...,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,Smart watch,1/18/2018 12:27,Standard Class
2,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,...,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,Smart watch,1/17/2018 12:06,Standard Class
3,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,...,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,Smart watch,1/16/2018 11:45,Standard Class
4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,...,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,Smart watch,1/15/2018 11:24,Standard Class

SALES CONTRIBUTION BY MARKET

In [4]:
# find the sales by market
market_sales = (
     df.groupby("Market")["Sales"]
     .sum()
)
market_sales

Market
Africa          2.294453e+06
Europe          1.087240e+07
LATAM           1.027761e+07
Pacific Asia    8.273744e+06
USCA            5.066529e+06
Name: Sales, dtype: float64

In [5]:
# find total sales
total_sales = df["Sales"].sum()
total_sales

36784735.01337984

In [6]:
# sales contribution in market
sales_contribution = (
     market_sales
     .div(total_sales)
     .mul(100)
     .reset_index(name="Sales Contribution %")
)
sales_contribution

         Market  Sales Contribution %
0        Africa              6.237514
1        Europe             29.556817
2         LATAM             27.939885
3  Pacific Asia             22.492329
4          USCA             13.773454

SALES CONTRIBUTION BY CUSTOMER SEGMENT

In [8]:
# find customer segment sales
customer_segment_sales = (
     df.groupby("Customer Segment")["Sales"]
     .sum()
)
customer_segment_sales

Customer Segment
Consumer       1.909579e+07
Corporate      1.116841e+07
Home Office    6.520538e+06
Name: Sales, dtype: float64

In [9]:
# find the total sales
total_sales = df["Sales"].sum()
total_sales

36784735.01337984

In [10]:
sales_contribution = (
     customer_segment_sales
     .div(total_sales)
.mul(100).reset_index(name="Sales Contribution %")
)
sales_contribution

  Customer Segment  Sales Contribution %
0         Consumer             51.912268
1        Corporate             30.361526
2      Home Office             17.726206

CONTRIBUTION WITHIN GROUP

In [30]:
# find the market and customer segment sales
market_segment_sales = (
    df.groupby(
        ["Market", "Customer Segment"]
    )["Sales"]
    .sum()
    .reset_index()
)

market_segment_sales

          Market Customer Segment         Sales
0         Africa         Consumer  1.187434e+06
1         Africa        Corporate  6.997575e+05
2         Africa      Home Office  4.072613e+05
3         Europe         Consumer  5.671565e+06
4         Europe        Corporate  3.303071e+06
5         Europe      Home Office  1.897761e+06
6          LATAM         Consumer  5.289639e+06
7          LATAM        Corporate  3.139115e+06
8          LATAM      Home Office  1.848859e+06
9   Pacific Asia         Consumer  4.286861e+06
10  Pacific Asia        Corporate  2.515593e+06
11  Pacific Asia      Home Office  1.471290e+06
12          USCA         Consumer  2.660291e+06
13          USCA        Corporate  1.510871e+06
14          USCA      Home Office  8.953663e+05

In [32]:
market_segment_sales["Market Total Sales"] = (
    market_segment_sales
    .groupby("Market")["Sales"]
    .transform("sum")
)

market_segment_sales["Market Total Sales"]

0     2.294453e+06
1     2.294453e+06
2     2.294453e+06
3     1.087240e+07
4     1.087240e+07
5     1.087240e+07
6     1.027761e+07
7     1.027761e+07
8     1.027761e+07
9     8.273744e+06
10    8.273744e+06
11    8.273744e+06
12    5.066529e+06
13    5.066529e+06
14    5.066529e+06
Name: Market Total Sales, dtype: float64

In [33]:
market_segment_sales["Market Contribution %"] = (
    market_segment_sales["Sales"]
    .div(market_segment_sales["Market Total Sales"])
    .mul(100)
)

market_segment_sales

,Market,Customer Segment,Sales,Market Total Sales,Market Contribution %
0,Africa,Consumer,1.187434e+06,2.294453e+06,51.752384
1,Africa,Corporate,6.997575e+05,2.294453e+06,30.497793
2,Africa,Home Office,4.072613e+05,2.294453e+06,17.749822
3,Europe,Consumer,5.671565e+06,1.087240e+07,52.164812
4,Europe,Corporate,3.303071e+06,1.087240e+07,30.380336
5,Europe,Home Office,1.897761e+06,1.087240e+07,17.454852
6,LATAM,Consumer,5.289639e+06,1.027761e+07,51.467582
7,LATAM,Corporate,3.139115e+06,1.027761e+07,30.543229
8,LATAM,Home Office,1.848859e+06,1.027761e+07,17.989189
9,Pacific Asia,Consumer,4.286861e+06,8.273744e+06,51.812829
10,Pacific Asia,Corporate,2.515593e+06,8.273744e+06,30.404526
11,Pacific Asia,Home Office,1.471290e+06,8.273744e+06,17.782645
12,USCA,Consumer,2.660291e+06,5.066529e+06,52.507177
13,USCA,Corporate,1.510871e+06,5.066529e+06,29.820639
14,USCA,Home Office,8.953663e+05,5.066529e+06,17.672184

FIND THE DOMINANT SEGMENT IN EACH MARKET

In [34]:
# find the highest contribution in each market
top_segment_by_market = market_segment_sales.loc[
     market_segment_sales.groupby("Market")["Market Contribution %"].idxmax()
]
top_segment_by_market

,Market,Customer Segment,Sales,Market Total Sales,Market Contribution %
0,Africa,Consumer,1.187434e+06,2.294453e+06,51.752384
3,Europe,Consumer,5.671565e+06,1.087240e+07,52.164812
6,LATAM,Consumer,5.289639e+06,1.027761e+07,51.467582
9,Pacific Asia,Consumer,4.286861e+06,8.273744e+06,51.812829
12,USCA,Consumer,2.660291e+06,5.066529e+06,52.507177

BUSINESS CHALLENGE

WHICH MARKET DEPENDS MOST HEAVILY ON ITS CONSUMER SEGMENT

In [35]:
# filter consumer
consumer_market = market_segment_sales[
     market_segment_sales["Customer Segment"] == "Consumer"
]
consumer_market

,Market,Customer Segment,Sales,Market Total Sales,Market Contribution %
0,Africa,Consumer,1.187434e+06,2.294453e+06,51.752384
3,Europe,Consumer,5.671565e+06,1.087240e+07,52.164812
6,LATAM,Consumer,5.289639e+06,1.027761e+07,51.467582
9,Pacific Asia,Consumer,4.286861e+06,8.273744e+06,51.812829
12,USCA,Consumer,2.660291e+06,5.066529e+06,52.507177

In [37]:
# find market with highest consumer contribution
consumer_market.loc[
    consumer_market["Market Contribution %"].idxmax()
]

Market                             USCA
Customer Segment               Consumer
Sales                    2660291.212957
Market Total Sales       5066528.710962
Market Contribution %         52.507177
Name: 12, dtype: object