HANDLING MISSING VALUES

In [44]:
import pandas as pd
import numpy as np

In [45]:
employee_data = {
      "Employee": ["Rahul", "Priya", "Amit", "Sneha"],
    "Department": ["Sales", "HR", np.nan, "Finance"],
    "Salary": [50000, np.nan, 70000, 55000]
}

employee_df = pd.DataFrame(employee_data)

In [46]:
employee_df

  Employee Department   Salary
0    Rahul      Sales  50000.0
1    Priya         HR      NaN
2     Amit        NaN  70000.0
3    Sneha    Finance  55000.0

ISNULL ()

In [47]:
employee_df.isnull()

   Employee  Department  Salary
0     False       False   False
1     False       False    True
2     False        True   False
3     False       False   False

In [48]:
employee_df.isnull().sum()

Employee      0
Department    1
Salary        1
dtype: int64

NOTNULL()

In [49]:
employee_df.notnull()

   Employee  Department  Salary
0      True        True    True
1      True        True   False
2      True       False    True
3      True        True    True

In [50]:
employee_df.notnull().sum()

Employee      4
Department    3
Salary        3
dtype: int64

FILLNA()

In [51]:
employee_df.fillna(0)

  Employee Department   Salary
0    Rahul      Sales  50000.0
1    Priya         HR      0.0
2     Amit          0  70000.0
3    Sneha    Finance  55000.0

In [52]:
employee_df["Salary"].fillna(0)

0    50000.0
1        0.0
2    70000.0
3    55000.0
Name: Salary, dtype: float64

In [53]:
employee_df["Department"].fillna("Unknown")

0      Sales
1         HR
2    Unknown
3    Finance
Name: Department, dtype: object

In [54]:
employee_df.fillna(
     {
          "Department" : "Unknown",
          "Salary" : 0
     }
)

  Employee Department   Salary
0    Rahul      Sales  50000.0
1    Priya         HR      0.0
2     Amit    Unknown  70000.0
3    Sneha    Finance  55000.0

DROPNA()

In [55]:
employee_df.dropna()

  Employee Department   Salary
0    Rahul      Sales  50000.0
3    Sneha    Finance  55000.0

In [56]:
employee_df.dropna(axis=1)

  Employee
0    Rahul
1    Priya
2     Amit
3    Sneha

REAL BUSINESS PROBLEM DATASET

In [57]:
import pandas as pd
import numpy as np

In [58]:
employee_data = {
    "Employee": ["Rahul", "Priya", "Amit", "Sneha", "Rohan", "Neha"],
    "Department": ["Sales", "HR", np.nan, "Finance", "IT", np.nan],
    "Salary": [50000, np.nan, 70000, 55000, np.nan, 62000],
    "Experience": [2, 5, 4, np.nan, 6, 3]
}

hr_df = pd.DataFrame(employee_data)

hr_df

  Employee Department   Salary  Experience
0    Rahul      Sales  50000.0         2.0
1    Priya         HR      NaN         5.0
2     Amit        NaN  70000.0         4.0
3    Sneha    Finance  55000.0         NaN
4    Rohan         IT      NaN         6.0
5     Neha        NaN  62000.0         3.0

In [59]:
hr_df.isnull().sum()

Employee      0
Department    2
Salary        2
Experience    1
dtype: int64

In [70]:
hr_df["Department"].fillna("Unknown")

0      Sales
1         HR
2    Unknown
3    Finance
4         IT
5    Unknown
Name: Department, dtype: object

In [71]:
hr_df["Salary"].fillna(0)

0    50000.0
1        0.0
2    70000.0
3    55000.0
4        0.0
5    62000.0
Name: Salary, dtype: float64

In [72]:
hr_df["Experience"].fillna(0)

0    2.0
1    5.0
2    4.0
3    0.0
4    6.0
5    3.0
Name: Experience, dtype: float64

In [77]:
clear_hr_df  = hr_df.fillna({
     "Department" : "Unknown",
     "Salary" : 0,
     "experience" : 0
})

clear_hr_df

  Employee Department   Salary  Experience
0    Rahul      Sales  50000.0         2.0
1    Priya         HR      0.0         5.0
2     Amit    Unknown  70000.0         4.0
3    Sneha    Finance  55000.0         NaN
4    Rohan         IT      0.0         6.0
5     Neha    Unknown  62000.0         3.0

In [78]:
clear_hr_df.isnull().sum()

Employee      0
Department    0
Salary        0
Experience    1
dtype: int64