ADVANCED GROUPBY AND BUSINESS ANALYSIS

In [49]:
import pandas as pd

In [50]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" , encoding="latin1")
df.head()

,Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,shipping date (DateOrders),Shipping Mode
0,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,...,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,Smart watch,02-03-2018 22:56,Standard Class
1,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,...,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,Smart watch,1/18/2018 12:27,Standard Class
2,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,...,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,Smart watch,1/17/2018 12:06,Standard Class
3,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,...,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,Smart watch,1/16/2018 11:45,Standard Class
4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,...,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,Smart watch,1/15/2018 11:24,Standard Class

MULTIPLE AGGREGATIONS

In [51]:
# find the category product with there total sales and profit as well as average sales and profit
product_category = (
     df.groupby("Category Name")
     [["Sales" , "Order Profit Per Order"]]
     .agg(["sum" , "mean"])
)
product_category.head()

                             Sales             Order Profit Per Order  \
                               sum        mean                    sum
Category Name
Accessories          133671.508825   75.096353           16643.520074
As Seen on  TV!       20597.939964  302.910882             714.429980
Baby                  12229.560379   59.080002            1525.029992
Baseball & Softball   94057.152543  148.824608           12762.130067
Basketball            27099.329343  404.467602            1845.670003


                          mean
Category Name
Accessories           9.350292
As Seen on  TV!      10.506323
Baby                  7.367295
Baseball & Softball  20.193244
Basketball           27.547313

In [52]:
high_profit = (
     df.groupby("Category Name")["Order Profit Per Order"]
     .sum().sort_values(ascending=False)
)
high_profit.head(1)

Category Name
Fishing    756220.76719
Name: Order Profit Per Order, dtype: float64

In [53]:
high_sales = (
     df.groupby("Category Name")["Sales"]
     .sum().sort_values(ascending=False)
)
high_sales.head(1)

Category Name
Fishing    6.929654e+06
Name: Sales, dtype: float64

In [54]:
high_avg_profit = (
     df.groupby("Category Name")["Order Profit Per Order"]
     .mean().sort_values(ascending=False)
)
high_avg_profit.head(1)

Category Name
Computers    157.594593
Name: Order Profit Per Order, dtype: float64

NAMED AGGREGATIONS

In [59]:
category_summary = df.groupby("Category Name").agg(
     Total_Sales = ("Sales" , "sum"),
     Average_Sales = ("Sales" , "mean"),
     Total_Profit = ("Order Profit Per Order" , "sum"),
     Average_Profit = ("Order Profit Per Order" , "mean"),
     No_of_Order = ("Order Id" , "count")
)
category_summary.head()

,Total_Sales,Average_Sales,Total_Profit,Average_Profit,No_of_Order
Category Name,,,,,
Accessories,133671.508825,75.096353,16643.520074,9.350292,1780
As Seen on TV!,20597.939964,302.910882,714.429980,10.506323,68
Baby,12229.560379,59.080002,1525.029992,7.367295,207
Baseball & Softball,94057.152543,148.824608,12762.130067,20.193244,632
Basketball,27099.329343,404.467602,1845.670003,27.547313,67

In [56]:
category_summary.sort_values(
     by="Total_Profit",
     ascending=False
).head(1)

,Total_Sales,Average_Sales,Total_Profit,Average_Profit,No_of_Order
Category Name,,,,,
Fishing,6.929654e+06,399.980011,756220.76719,43.649106,17325

In [57]:
category_summary.sort_values(
     by="Average_Profit",
     ascending=False
).head(1)

,Total_Sales,Average_Sales,Total_Profit,Average_Profit,No_of_Order
Category Name,,,,,
Computers,663000.0,1500.0,69656.810171,157.594593,442

GROUPED BUSINESS METRICS

In [60]:
market_segment_metrics = (
     df.groupby(["Market" , "Customer Segment"])["Sales"]
     .sum().reset_index()
)
market_segment_metrics

          Market Customer Segment         Sales
0         Africa         Consumer  1.187434e+06
1         Africa        Corporate  6.997575e+05
2         Africa      Home Office  4.072613e+05
3         Europe         Consumer  5.671565e+06
4         Europe        Corporate  3.303071e+06
5         Europe      Home Office  1.897761e+06
6          LATAM         Consumer  5.289639e+06
7          LATAM        Corporate  3.139115e+06
8          LATAM      Home Office  1.848859e+06
9   Pacific Asia         Consumer  4.286861e+06
10  Pacific Asia        Corporate  2.515593e+06
11  Pacific Asia      Home Office  1.471290e+06
12          USCA         Consumer  2.660291e+06
13          USCA        Corporate  1.510871e+06
14          USCA      Home Office  8.953663e+05

In [61]:
# which customer segment has the highest sales within each market
market_segment_metrics.loc[
     market_segment_metrics.groupby("Market")["Sales"].idxmax()
]

          Market Customer Segment         Sales
0         Africa         Consumer  1.187434e+06
3         Europe         Consumer  5.671565e+06
6          LATAM         Consumer  5.289639e+06
9   Pacific Asia         Consumer  4.286861e+06
12          USCA         Consumer  2.660291e+06

RANKING WITHIN GROUPS

In [62]:
# for each market , rank the customer segment acco. to their sales 
market_segment_metrics["Sales Rank"] =(
     market_segment_metrics.groupby("Market")["Sales"]
     .rank(
          ascending=False ,
          method="dense"
     )
)

In [63]:
market_segment_metrics.sort_values(
     ["Market" , "Sales Rank"]
)

          Market Customer Segment         Sales  Sales Rank
0         Africa         Consumer  1.187434e+06         1.0
1         Africa        Corporate  6.997575e+05         2.0
2         Africa      Home Office  4.072613e+05         3.0
3         Europe         Consumer  5.671565e+06         1.0
4         Europe        Corporate  3.303071e+06         2.0
5         Europe      Home Office  1.897761e+06         3.0
6          LATAM         Consumer  5.289639e+06         1.0
7          LATAM        Corporate  3.139115e+06         2.0
8          LATAM      Home Office  1.848859e+06         3.0
9   Pacific Asia         Consumer  4.286861e+06         1.0
10  Pacific Asia        Corporate  2.515593e+06         2.0
11  Pacific Asia      Home Office  1.471290e+06         3.0
12          USCA         Consumer  2.660291e+06         1.0
13          USCA        Corporate  1.510871e+06         2.0
14          USCA      Home Office  8.953663e+05         3.0

BUSINESS CHALLENGE :-
                    WHICH CUSTOMER SEGMENT HAS HIGHEST AVERAGE ORDER VLAUE IN EACH MARKET

In [64]:
# find the average market segment
average_market_segmet = (
     df.groupby(["Market" , "Customer Segment"])["Sales"]
     .mean().reset_index(name="Average Sales")
)
average_market_segmet

          Market Customer Segment  Average Sales
0         Africa         Consumer     197.675061
1         Africa        Corporate     198.343967
2         Africa      Home Office     195.892890
3         Europe         Consumer     217.234769
4         Europe        Corporate     215.703694
5         Europe      Home Office     214.897608
6          LATAM         Consumer     198.873554
7          LATAM        Corporate     199.956357
8          LATAM      Home Office     198.866217
9   Pacific Asia         Consumer     201.412362
10  Pacific Asia        Corporate     201.118691
11  Pacific Asia      Home Office     197.012646
12          USCA         Consumer     196.956483
13          USCA        Corporate     195.177785
14          USCA      Home Office     196.740556

In [66]:
# find the highest sales in every market
average_market_segmet.loc[
     average_market_segmet.groupby("Market")["Average Sales"].idxmax()
]

          Market Customer Segment  Average Sales
1         Africa        Corporate     198.343967
3         Europe         Consumer     217.234769
7          LATAM        Corporate     199.956357
9   Pacific Asia         Consumer     201.412362
12          USCA         Consumer     196.956483