SECOND MINI PROJECT : DEPARTMENT SALES ANALYSIS

In [1]:
import pandas as pd

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_17100\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
employee_data = {
    "Employee": [
        "Rahul","Priya","Amit","Sneha","Rohan",
        "Neha","Karan","Pooja","Vikram","Anjali"
    ],
    "Department": [
        "Sales","HR","IT","Finance","IT",
        "Sales","HR","Finance","IT","Sales"
    ],
    "Salary": [
        50000,65000,70000,55000,80000,
        62000,68000,72000,90000,58000
    ],
    "Experience":[
        2,5,4,3,6,
        4,5,7,8,3
    ]
}

employee_df = pd.DataFrame(employee_data)

employee_df

  Employee Department  Salary  Experience
0    Rahul      Sales   50000           2
1    Priya         HR   65000           5
2     Amit         IT   70000           4
3    Sneha    Finance   55000           3
4    Rohan         IT   80000           6
5     Neha      Sales   62000           4
6    Karan         HR   68000           5
7    Pooja    Finance   72000           7
8   Vikram         IT   90000           8
9   Anjali      Sales   58000           3

In [3]:
employee_df.head()

  Employee Department  Salary  Experience
0    Rahul      Sales   50000           2
1    Priya         HR   65000           5
2     Amit         IT   70000           4
3    Sneha    Finance   55000           3
4    Rohan         IT   80000           6

In [4]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    10 non-null     object
 1   Department  10 non-null     object
 2   Salary      10 non-null     int64
 3   Experience  10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes

In [7]:
# department wise total salary
department_total_salary = employee_df.groupby("Department")["Salary"].sum()

department_total_salary

Department
Finance    127000
HR         133000
IT         240000
Sales      170000
Name: Salary, dtype: int64

In [9]:
# department wise average salary
department_average_salary = employee_df.groupby("Department")["Salary"].mean()

department_average_salary

Department
Finance    63500.000000
HR         66500.000000
IT         80000.000000
Sales      56666.666667
Name: Salary, dtype: float64

In [ ]:
# department wise employee count
department_count_salary = employee_df.groupby("Department")["Salary"].count()

department_count_salary

Department
Finance    2
HR         2
IT         3
Sales      3
Name: Salary, dtype: int64

In [12]:
# department wise maximum salary
department_max_salary = employee_df.groupby("Department")["Salary"].max()

department_max_salary

Department
Finance    72000
HR         68000
IT         90000
Sales      62000
Name: Salary, dtype: int64

In [13]:
# department wise minimum salary
department_min_salary = employee_df.groupby("Department")["Salary"].min()

department_min_salary

Department
Finance    55000
HR         65000
IT         70000
Sales      50000
Name: Salary, dtype: int64

In [14]:
# professional calculation
employee_df.groupby("Department")["Salary"].agg(
    ["sum", "mean", "count", "min", "max"]
)

               sum          mean  count    min    max
Department
Finance     127000  63500.000000      2  55000  72000
HR          133000  66500.000000      2  65000  68000
IT          240000  80000.000000      3  70000  90000
Sales       170000  56666.666667      3  50000  62000

In [ ]:
# employee with highest salary
employee_df.sort_values(
     by = "Salary",
     ascending=False
).head(1)

  Employee Department  Salary  Experience
8   Vikram         IT   90000           8

In [21]:
# employee with lowest salary
employee_df.sort_values(
     by="Salary"
).head(1)

  Employee Department  Salary  Experience
0    Rahul      Sales   50000           2