## DAY 30 : ADVANCED NUMPY

In [1]:
import pandas as pd
import numpy as np

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_10012\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# Create business dataset
sales =  np.array([
     1200,1500,1100,1800,
     900,1300,1250,1600,
     2000,2200,2100,2500
])
sales

array([1200, 1500, 1100, 1800,  900, 1300, 1250, 1600, 2000, 2200, 2100,
       2500])

In [10]:
# reshape the array
regional_sales = sales.reshape(3,4)
regional_sales

array([[1200, 1500, 1100, 1800],
       [ 900, 1300, 1250, 1600],
       [2000, 2200, 2100, 2500]])

In [11]:
regional_sales.shape

(3, 4)

In [12]:
# reshape into 4 rows and 3 columns
sales.reshape(4,3)

array([[1200, 1500, 1100],
       [1800,  900, 1300],
       [1250, 1600, 2000],
       [2200, 2100, 2500]])

In [13]:
# Flatten array 
regional_sales.flatten()

array([1200, 1500, 1100, 1800,  900, 1300, 1250, 1600, 2000, 2200, 2100,
       2500])

In [14]:
# management wants to calculate the total sales for each region
regional_sales.sum(axis=1)

array([5600, 5050, 8800])

### BOOLEAN OPERATIONS AND np.where()

In [16]:
# Find sales that are at least 1,200 and below 2,000.
sales [
     (sales >= 1200) &
     (sales < 2000)
]

array([1200, 1500, 1800, 1300, 1250, 1600])

In [17]:
# Find sales below 1,000 or at least 2,200.
sales [
     (sales < 1000) | 
     (sales >= 2200)
 ]

array([ 900, 2200, 2500])

In [18]:
# classify sales using np.where()
sales_status = np.where(
     sales >= 1800 ,
     "High" ,
     "Standard"
)
sales_status

array(['Standard', 'Standard', 'Standard', 'High', 'Standard', 'Standard',
       'Standard', 'Standard', 'High', 'High', 'High', 'High'],
      dtype='<U8')

In [19]:
# count each category
np.unique(sales_status, return_counts=True)

(array(['High', 'Standard'], dtype='<U8'), array([5, 7], dtype=int64))

In [20]:
# Sales ≥ 2,000 → "Excellent"
# Sales ≥ 1,500 → "Good"
# Otherwise → "Needs Improvement"

sales_performance =np.select(
     [
          sales >= 2000 ,
          sales >= 1500
     ],
     [
          "Excellent",
          "Good"
     ],
     default="Need Improvemnet"
)
sales_performance

array(['Need Improvemnet', 'Good', 'Need Improvemnet', 'Good',
       'Need Improvemnet', 'Need Improvemnet', 'Need Improvemnet', 'Good',
       'Excellent', 'Excellent', 'Excellent', 'Excellent'], dtype='<U16')

In [21]:
np.unique(sales_performance, return_counts=True)

(array(['Excellent', 'Good', 'Need Improvemnet'], dtype='<U16'),
 array([4, 3, 5], dtype=int64))

### BROADCASTING AND NUMPY WITH PANDAS

In [22]:
# A 10% price increase across every sales value:
increased_sales = sales * 1.10
increased_sales

array([1320., 1650., 1210., 1980.,  990., 1430., 1375., 1760., 2200.,
       2420., 2310., 2750.])

In [23]:
regional_adjustments = np.array([1.10, 1.05, 1.15])

adjusted_regional_sales = regional_sales * regional_adjustments[:, np.newaxis]

adjusted_regional_sales

array([[1320. , 1650. , 1210. , 1980. ],
       [ 945. , 1365. , 1312.5, 1680. ],
       [2300. , 2530. , 2415. , 2875. ]])

In [25]:
# Convert NumPy results into a Pandas DataFrame
sales_df = pd.DataFrame(
     regional_sales ,
     index=["Region A" , "Region B" , "Region C"],
     columns=["Day 1"  , "Day 2" , "Day 3" , "Day 4"]
)
sales_df

          Day 1  Day 2  Day 3  Day 4
Region A   1200   1500   1100   1800
Region B    900   1300   1250   1600
Region C   2000   2200   2100   2500

In [26]:
# add regional KPI
sales_df["Total_Sales"] = sales_df.sum(axis=1)

sales_df

          Day 1  Day 2  Day 3  Day 4  Total_Sales
Region A   1200   1500   1100   1800         5600
Region B    900   1300   1250   1600         5050
Region C   2000   2200   2100   2500         8800

In [29]:
# Calculate contribution percentage using NumPy
sales_df["Contribution_%"] = (
     np.divide(
          sales_df["Total_Sales"],
          sales_df["Total_Sales"].sum()
     ) * 100
)
sales_df

          Day 1  Day 2  Day 3  Day 4  Total_Sales  Contribution_%
Region A   1200   1500   1100   1800         5600       28.791774
Region B    900   1300   1250   1600         5050       25.964010
Region C   2000   2200   2100   2500         8800       45.244216