MINI PROJECT 03 - HR EMPLOYEE DATA TRANSFORMATIONS

In [2]:
import pandas as pd

In [4]:
employee_df = pd.read_csv("employee_data.csv")
employee_df

  Employee Department  Experience  Salary
0   Rahul       Sales           2   50000
1   Priya          HR           5   65000
2    Amit          IT           4   70000
3    Sneha    Finance           3   55000
4    Rohan         HR           6   80000

In [8]:
# Department Code
employee_df["Department_Code"]= employee_df["Department"].map({
     "Sales" : "S",
     "HR" : "H",
     "IT" : "I",
     "Finance" : "F"
})
employee_df

  Employee Department  Experience  Salary Department_Code
0   Rahul       Sales           2   50000               S
1   Priya          HR           5   65000               H
2    Amit          IT           4   70000               I
3    Sneha    Finance           3   55000               F
4    Rohan         HR           6   80000               H

In [11]:
# Replace Department Name
employee_df["Department_name"] = employee_df["Department"].replace({
     "HR" : "Human Resources" , 
     "IT" : "Information Technology"
})
employee_df

,Employee,Department,Experience,Salary,Department_Code,Department_name
0,Rahul,Sales,2,50000,S,Sales
1,Priya,HR,5,65000,H,Human Resources
2,Amit,IT,4,70000,I,Information Technology
3,Sneha,Finance,3,55000,F,Finance
4,Rohan,HR,6,80000,H,Human Resources

In [13]:
# Increase salary by 10 %
employee_df["Updated_Salary"] = employee_df["Salary"].apply(
     lambda salary : salary * 1.10
)
employee_df

,Employee,Department,Experience,Salary,Department_Code,Department_name,Updated_Salary
0,Rahul,Sales,2,50000,S,Sales,55000.0
1,Priya,HR,5,65000,H,Human Resources,71500.0
2,Amit,IT,4,70000,I,Information Technology,77000.0
3,Sneha,Finance,3,55000,F,Finance,60500.0
4,Rohan,HR,6,80000,H,Human Resources,88000.0

In [15]:
# Salary Status
employee_df["Salary_Status"] = employee_df["Salary"].apply(
     lambda salary : "High"
     if salary >= 60000 else "Low"
)
employee_df

,Employee,Department,Experience,Salary,Department_Code,Department_name,Updated_Salary,Salary_Status
0,Rahul,Sales,2,50000,S,Sales,55000.0,Low
1,Priya,HR,5,65000,H,Human Resources,71500.0,High
2,Amit,IT,4,70000,I,Information Technology,77000.0,High
3,Sneha,Finance,3,55000,F,Finance,60500.0,Low
4,Rohan,HR,6,80000,H,Human Resources,88000.0,High

In [16]:
# Increase Bonus
employee_df["Bonus"] = employee_df["Salary"].apply(
     lambda bonus : bonus * 5000
)
employee_df

,Employee,Department,Experience,Salary,Department_Code,Department_name,Updated_Salary,Salary_Status,Bonus
0,Rahul,Sales,2,50000,S,Sales,55000.0,Low,250000000
1,Priya,HR,5,65000,H,Human Resources,71500.0,High,325000000
2,Amit,IT,4,70000,I,Information Technology,77000.0,High,350000000
3,Sneha,Finance,3,55000,F,Finance,60500.0,Low,275000000
4,Rohan,HR,6,80000,H,Human Resources,88000.0,High,400000000