GROUP BY AND AGGREGATION

In [1]:
import pandas as pd

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_1708\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
employee_data = {
    "Employee": [
        "Rahul",
        "Priya",
        "Amit",
        "Sneha",
        "Rohan",
        "Neha"
    ],
    "Department": [
        "Sales",
        "HR",
        "IT",
        "Finance",
        "IT",
        "Sales"
    ],
    "Salary": [
        50000,
        65000,
        70000,
        55000,
        80000,
        62000
    ]
}

employee_df = pd.DataFrame(employee_data)

GROUP BY()

In [4]:
employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000
4    Rohan         IT   80000
5     Neha      Sales   62000

In [18]:
# aggregate functions like : sum() , count() , min() , max() , mean()
department_salary = employee_df.groupby("Department")["Salary"].sum()

department_salary

Department
Finance     55000
HR          65000
IT         150000
Sales      112000
Name: Salary, dtype: int64

In [26]:
department_average_salary = employee_df.groupby("Department")["Salary"].mean()
department_average_salary

Department
Finance    55000.0
HR         65000.0
IT         75000.0
Sales      56000.0
Name: Salary, dtype: float64

In [30]:
department_count_salary = employee_df.groupby("Department")["Salary"].count()
department_count_salary

Department
Finance    1
HR         1
IT         2
Sales      2
Name: Salary, dtype: int64

In [31]:
department_max_salary = employee_df.groupby("Department")["Salary"].max()
department_max_salary

Department
Finance    55000
HR         65000
IT         80000
Sales      62000
Name: Salary, dtype: int64

In [32]:
department_min_salary = employee_df.groupby("Department")["Salary"].min()
department_min_salary

Department
Finance    55000
HR         65000
IT         70000
Sales      50000
Name: Salary, dtype: int64

In [33]:
employee_df.groupby("Department")["Salary"].agg(
     ["sum" , "count" , "mean" , "min" , "max"]
)

               sum  count     mean    min    max
Department
Finance      55000      1  55000.0  55000  55000
HR           65000      1  65000.0  65000  65000
IT          150000      2  75000.0  70000  80000
Sales       112000      2  56000.0  50000  62000