MERGE() , JOIN() , CONCAT()

In [9]:
import pandas as pd

In [10]:
employee_df = pd.DataFrame({
     "Employee_ID" : [101,102,103,104],
     "Employee" : ["Rahul" , "Priya" , "Amit" , "Sneha"],
     "Department_ID" : [1,2,3,2]
})

employee_df

   Employee_ID Employee  Department_ID
0          101    Rahul              1
1          102    Priya              2
2          103     Amit              3
3          104    Sneha              2

In [11]:
department_df = pd.DataFrame({
    "Department_ID": [1, 2, 3],
    "Department": ["Sales", "HR", "IT"]
})

department_df

   Department_ID Department
0              1      Sales
1              2         HR
2              3         IT

In [12]:
merge_df = pd.merge(
     employee_df,
     department_df,
     on="Department_ID"
)

merge_df

   Employee_ID Employee  Department_ID Department
0          101    Rahul              1      Sales
1          102    Priya              2         HR
2          103     Amit              3         IT
3          104    Sneha              2         HR

TYPES OF MERGE ;- INNER JOIN , LEFT JOIN , RIGHT JOIN , OUTER JOIN

In [13]:
employee_df = pd.DataFrame({
    "Employee_ID":[101,102,103,104],
    "Employee":["Rahul","Priya","Amit","Sneha"],
    "Department_ID":[1,2,3,5]
})

employee_df

   Employee_ID Employee  Department_ID
0          101    Rahul              1
1          102    Priya              2
2          103     Amit              3
3          104    Sneha              5

In [14]:
department_df = pd.DataFrame({
    "Department_ID":[1,2,3,4],
    "Department":["Sales","HR","IT","Finance"]
})

department_df

   Department_ID Department
0              1      Sales
1              2         HR
2              3         IT
3              4    Finance

In [16]:
inner_df = pd.merge(
     employee_df , department_df ,
     on="Department_ID" , 
     how="inner"
)
inner_df

   Employee_ID Employee  Department_ID Department
0          101    Rahul              1      Sales
1          102    Priya              2         HR
2          103     Amit              3         IT

In [17]:
left_df = pd.merge(
     employee_df , department_df,
     on="Department_ID",
     how="left"
)
left_df

   Employee_ID Employee  Department_ID Department
0          101    Rahul              1      Sales
1          102    Priya              2         HR
2          103     Amit              3         IT
3          104    Sneha              5        NaN

In [18]:
right_df = pd.merge(
     employee_df , department_df,
     on="Department_ID",
     how="right"
)
right_df

   Employee_ID Employee  Department_ID Department
0        101.0    Rahul              1      Sales
1        102.0    Priya              2         HR
2        103.0     Amit              3         IT
3          NaN      NaN              4    Finance

In [19]:
outer_df = pd.merge(
     employee_df , department_df,
     on="Department_ID",
     how="outer"
)
outer_df

   Employee_ID Employee  Department_ID Department
0        101.0    Rahul              1      Sales
1        102.0    Priya              2         HR
2        103.0     Amit              3         IT
3          NaN      NaN              4    Finance
4        104.0    Sneha              5        NaN

CONCAT ()    -
          BY ROW WISE
          BY COLUMN WISE

In [20]:
employee1 = pd.DataFrame({
    "Employee":["Rahul","Priya"],
    "Salary":[50000,65000]
})

employee1

  Employee  Salary
0    Rahul   50000
1    Priya   65000

In [21]:
employee2 = pd.DataFrame({
    "Employee":["Amit","Sneha"],
    "Salary":[70000,55000]
})

employee2

  Employee  Salary
0     Amit   70000
1    Sneha   55000

In [28]:
# conact() by row wise
pd.concat(
     [employee1 , employee2],
     ignore_index=False
)

  Employee  Salary
0    Rahul   50000
1    Priya   65000
0     Amit   70000
1    Sneha   55000

In [33]:
# concat() by column wise
employee_info = pd.DataFrame({
    "Department":["Sales","HR"]
})

pd.concat(
    [employee1, employee_info],
    axis=1 
)

  Employee  Salary Department
0    Rahul   50000      Sales
1    Priya   65000         HR

JOIN()

In [38]:
employee_df = pd.DataFrame(
    {
        "Employee":["Rahul","Priya"],
        "Salary":[50000,65000]
    },
    index=[1,2]
)
employee_df

  Employee  Salary
1    Rahul   50000
2    Priya   65000

In [42]:
department_df = pd.DataFrame({
     "Department":["Sales" , "HR"]
} , index=[1,2]
)
department_df

  Department
1      Sales
2         HR

In [43]:
employee_df.join(department_df)

  Employee  Salary Department
1    Rahul   50000      Sales
2    Priya   65000         HR