DAY 23 ADAVANCED FILTERING AND CONDITIONAL ANALYSIS

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" , encoding="latin1")
df.shape

(180519, 31)

## Single-Condition Filtering

In [9]:
## Which orders have sales greater than 500?
high_sales_orders = df[df["Sales"] > 500]
high_sales_orders.shape

(972, 31)

In [10]:
high_sales_orders[["Order Id" , "Sales" , "Customer Segment" , "Order Region"]].head()

     Order Id       Sales Customer Segment     Order Region
152     70734  1500.00000         Consumer  Northern Europe
155     70769  1500.00000         Consumer  Northern Europe
160     70534  1500.00000         Consumer   Western Europe
172     70544  1500.00000         Consumer  Northern Europe
174     68879   999.98999         Consumer   Western Europe

## Multi-Condition Filtering

In [18]:
# Find orders where Sales > 500 AND the customer is in the Consumer segment.
consumer_high_sales = df[(df["Sales"] > 500) & (df["Customer Segment"] == "Consumer")]
consumer_high_sales.shape

(520, 31)

In [17]:
consumer_high_sales[["Order Id" , "Sales" , "Customer Segment" ,"Order Region"]].head(10)

      Order Id        Sales Customer Segment     Order Region
152      70734  1500.000000         Consumer  Northern Europe
155      70769  1500.000000         Consumer  Northern Europe
160      70534  1500.000000         Consumer   Western Europe
172      70544  1500.000000         Consumer  Northern Europe
174      68879   999.989990         Consumer   Western Europe
1594     70795  1500.000000         Consumer   Western Europe
3495     74536  1500.000000         Consumer       South Asia
3496     74570  1500.000000         Consumer     Eastern Asia
3623     75144   532.580017         Consumer     Eastern Asia
3627     75131   532.580017         Consumer       South Asia

## OR Condition + isin()

In [25]:
# Find orders from either Consumer OR Corporate customers where Sales > 500.
consumer_corporate_high_sales = df[
     (df["Sales"] > 500) &
     (df["Customer Segment"].isin(["Consumer" , "Corporate"]))
]
consumer_corporate_high_sales.shape

(828, 31)

In [26]:
consumer_corporate_high_sales[["Order Id" , "Sales" , "Customer Segment" , "Order Region"]].head(10)

      Order Id        Sales Customer Segment     Order Region
152      70734  1500.000000         Consumer  Northern Europe
155      70769  1500.000000         Consumer  Northern Europe
160      70534  1500.000000         Consumer   Western Europe
172      70544  1500.000000         Consumer  Northern Europe
174      68879   999.989990         Consumer   Western Europe
1594     70795  1500.000000         Consumer   Western Europe
2325     71986   532.580017        Corporate          Oceania
2328     71894   532.580017        Corporate     Eastern Asia
2330     71947   532.580017        Corporate   Southeast Asia
2331     71821   532.580017        Corporate   Southeast Asia

## between()

In [27]:
# Find transactions where Sales is between 100 and 500.
medium_sales_orders = df[
     df["Sales"].between(100 , 500)
]
medium_sales_orders.shape

(144631, 31)

In [29]:
medium_sales_orders["Sales"].agg(["min" , "max"])

min    100.0
max    500.0
Name: Sales, dtype: float64

## Combine Multiple Filtering Techniques

In [31]:
## Find Consumer or Corporate transactions where Sales is between 100 and 500, and the order has no late-delivery risk.
target_orders = df[
     (df["Sales"].between(100 , 500)) &
     (df["Customer Segment"].isin(["Consumer" , "Corporate"])) &
     (df["Late_delivery_risk"] == 0)
]
target_orders.shape

(53917, 31)

In [32]:
target_orders[
     ["Order Id" , "Sales" , "Customer Segment" , "Late_delivery_risk" , "Order Region"]
].head(10)

    Order Id   Sales Customer Segment  Late_delivery_risk    Order Region
0      77202  327.75         Consumer                   0  Southeast Asia
2      75938  327.75         Consumer                   0      South Asia
4      75936  327.75        Corporate                   0         Oceania
5      75935  327.75         Consumer                   0         Oceania
10     75930  327.75        Corporate                   0    Eastern Asia
19     75921  327.75         Consumer                   0      South Asia
20     75920  327.75        Corporate                   0      South Asia
23     75917  327.75        Corporate                   0         Oceania
24     75916  327.75        Corporate                   0         Oceania
27     75913  327.75        Corporate                   0    Eastern Asia

FILTERING BUSINESS CHALLENGE

In [39]:
high_value_transactions = df[
     (df["Sales"] > 500) & 
     (df["Customer Segment"].isin(["Consumer" , "Corporate"])) &
     (df["Delivery Status"]== "Late delivery") &
     (df["Order Region"].isin(["Western Europe" , "Central America" , "Southern Europe"]))
]
high_value_transactions.shape

(134, 31)

In [40]:
high_value_transactions[
     ["Order Id" , "Sales" , "Customer Segment" , "Delivery Status" , "Order Region"]
].head(10)

       Order Id       Sales Customer Segment Delivery Status    Order Region
160       70534  1500.00000         Consumer   Late delivery  Western Europe
174       68879   999.98999         Consumer   Late delivery  Western Europe
1594      70795  1500.00000         Consumer   Late delivery  Western Europe
5774      70639  1500.00000         Consumer   Late delivery  Western Europe
5836      68773   599.98999         Consumer   Late delivery  Western Europe
7961      70850  1500.00000        Corporate   Late delivery  Western Europe
9603      70786  1500.00000         Consumer   Late delivery  Western Europe
9611      70600  1500.00000         Consumer   Late delivery  Western Europe
12516     70560  1500.00000         Consumer   Late delivery  Western Europe
12528     70609  1500.00000         Consumer   Late delivery  Western Europe