MINI PROJECTS 04 - CUSTOMER DATA CLEANING AND STANDARDIZATION

In [2]:
import pandas as pd

In [3]:
customer_df = pd.read_csv("customer_data.csv")

customer_df

   Customer_ID       Full_Name               Email         City
0          101   Rahul Sharma    RAHUL@Company.COM        pune
1          102     PRIYA PATEL   PRIYA@Company.COM       MUMBAI
2          103      amit verma    amit@Company.COM   bangalore
3          104    Sneha Joshi    Sneha@Company.COM        Delhi
4          105     rohan singh   ROHAN@Company.COM   hyderabad
5          106      NEHA GUPTA    NEHA@Company.COM         PUNE
6          107    Akash Patel    AKASH@Company.COM       Mumbai
7          108      pooja shah   POOJA@Company.COM        pune
8          109      VIKRAM RAO  VIKRAM@Company.COM      CHENNAI
9          110    Divya Mehta    DIVYA@Company.COM   Ahmedabad

DATASET OVERVIEW

In [4]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  10 non-null     int64
 1   Full_Name    10 non-null     object
 2   Email        10 non-null     object
 3   City         10 non-null     object
dtypes: int64(1), object(3)
memory usage: 448.0+ bytes

In [5]:
customer_df.head()

   Customer_ID       Full_Name              Email         City
0          101   Rahul Sharma   RAHUL@Company.COM        pune
1          102     PRIYA PATEL  PRIYA@Company.COM       MUMBAI
2          103      amit verma   amit@Company.COM   bangalore
3          104    Sneha Joshi   Sneha@Company.COM        Delhi
4          105     rohan singh  ROHAN@Company.COM   hyderabad

In [8]:
customer_df.shape

(10, 4)

REMOVE EXTRASPACES

In [12]:
# remove extra spaces
customer_df["Full_Name"] = customer_df["Full_Name"].str.strip()
customer_df

   Customer_ID     Full_Name               Email         City
0          101  Rahul Sharma   RAHUL@Company.COM        pune
1          102   PRIYA PATEL   PRIYA@Company.COM       MUMBAI
2          103    amit verma    amit@Company.COM   bangalore
3          104   Sneha Joshi   Sneha@Company.COM        Delhi
4          105   rohan singh   ROHAN@Company.COM   hyderabad
5          106    NEHA GUPTA    NEHA@Company.COM         PUNE
6          107   Akash Patel   AKASH@Company.COM       Mumbai
7          108    pooja shah   POOJA@Company.COM        pune
8          109    VIKRAM RAO  VIKRAM@Company.COM      CHENNAI
9          110   Divya Mehta   DIVYA@Company.COM   Ahmedabad

In [14]:
customer_df["City"] = customer_df["City"].str.strip()
customer_df

   Customer_ID     Full_Name               Email       City
0          101  Rahul Sharma   RAHUL@Company.COM       pune
1          102   PRIYA PATEL   PRIYA@Company.COM     MUMBAI
2          103    amit verma    amit@Company.COM  bangalore
3          104   Sneha Joshi   Sneha@Company.COM      Delhi
4          105   rohan singh   ROHAN@Company.COM  hyderabad
5          106    NEHA GUPTA    NEHA@Company.COM       PUNE
6          107   Akash Patel   AKASH@Company.COM     Mumbai
7          108    pooja shah   POOJA@Company.COM       pune
8          109    VIKRAM RAO  VIKRAM@Company.COM    CHENNAI
9          110   Divya Mehta   DIVYA@Company.COM  Ahmedabad

CONVERT INTO TITLES

In [16]:
customer_df["Full_Name"] = customer_df["Full_Name"].str.title()
customer_df

   Customer_ID     Full_Name               Email       City
0          101  Rahul Sharma   RAHUL@Company.COM       pune
1          102   Priya Patel   PRIYA@Company.COM     MUMBAI
2          103    Amit Verma    amit@Company.COM  bangalore
3          104   Sneha Joshi   Sneha@Company.COM      Delhi
4          105   Rohan Singh   ROHAN@Company.COM  hyderabad
5          106    Neha Gupta    NEHA@Company.COM       PUNE
6          107   Akash Patel   AKASH@Company.COM     Mumbai
7          108    Pooja Shah   POOJA@Company.COM       pune
8          109    Vikram Rao  VIKRAM@Company.COM    CHENNAI
9          110   Divya Mehta   DIVYA@Company.COM  Ahmedabad

In [17]:
customer_df["City"] = customer_df["City"].str.title()
customer_df

   Customer_ID     Full_Name               Email       City
0          101  Rahul Sharma   RAHUL@Company.COM       Pune
1          102   Priya Patel   PRIYA@Company.COM     Mumbai
2          103    Amit Verma    amit@Company.COM  Bangalore
3          104   Sneha Joshi   Sneha@Company.COM      Delhi
4          105   Rohan Singh   ROHAN@Company.COM  Hyderabad
5          106    Neha Gupta    NEHA@Company.COM       Pune
6          107   Akash Patel   AKASH@Company.COM     Mumbai
7          108    Pooja Shah   POOJA@Company.COM       Pune
8          109    Vikram Rao  VIKRAM@Company.COM    Chennai
9          110   Divya Mehta   DIVYA@Company.COM  Ahmedabad

FORMAT EMAILS

In [18]:
customer_df["Email"] = customer_df["Email"].str.lower()
customer_df

   Customer_ID     Full_Name               Email       City
0          101  Rahul Sharma   rahul@company.com       Pune
1          102   Priya Patel   priya@company.com     Mumbai
2          103    Amit Verma    amit@company.com  Bangalore
3          104   Sneha Joshi   sneha@company.com      Delhi
4          105   Rohan Singh   rohan@company.com  Hyderabad
5          106    Neha Gupta    neha@company.com       Pune
6          107   Akash Patel   akash@company.com     Mumbai
7          108    Pooja Shah   pooja@company.com       Pune
8          109    Vikram Rao  vikram@company.com    Chennai
9          110   Divya Mehta   divya@company.com  Ahmedabad

CHANGE DOMAIN

In [19]:
customer_df["Email"] = customer_df["Email"].str.replace(
     "company" , "techcorp"
)
customer_df

   Customer_ID     Full_Name                Email       City
0          101  Rahul Sharma   rahul@techcorp.com       Pune
1          102   Priya Patel   priya@techcorp.com     Mumbai
2          103    Amit Verma    amit@techcorp.com  Bangalore
3          104   Sneha Joshi   sneha@techcorp.com      Delhi
4          105   Rohan Singh   rohan@techcorp.com  Hyderabad
5          106    Neha Gupta    neha@techcorp.com       Pune
6          107   Akash Patel   akash@techcorp.com     Mumbai
7          108    Pooja Shah   pooja@techcorp.com       Pune
8          109    Vikram Rao  vikram@techcorp.com    Chennai
9          110   Divya Mehta   divya@techcorp.com  Ahmedabad

EXTRACT NAME

In [21]:
customer_df["First_Name"] = customer_df["Full_Name"].str.split().str[0]
customer_df

   Customer_ID     Full_Name                Email       City First_Name
0          101  Rahul Sharma   rahul@techcorp.com       Pune      Rahul
1          102   Priya Patel   priya@techcorp.com     Mumbai      Priya
2          103    Amit Verma    amit@techcorp.com  Bangalore       Amit
3          104   Sneha Joshi   sneha@techcorp.com      Delhi      Sneha
4          105   Rohan Singh   rohan@techcorp.com  Hyderabad      Rohan
5          106    Neha Gupta    neha@techcorp.com       Pune       Neha
6          107   Akash Patel   akash@techcorp.com     Mumbai      Akash
7          108    Pooja Shah   pooja@techcorp.com       Pune      Pooja
8          109    Vikram Rao  vikram@techcorp.com    Chennai     Vikram
9          110   Divya Mehta   divya@techcorp.com  Ahmedabad      Divya

In [22]:
customer_df["Last_Name"] = customer_df["Full_Name"].str.split().str[1]
customer_df

,Customer_ID,Full_Name,Email,City,First_Name,Last_Name
0,101,Rahul Sharma,rahul@techcorp.com,Pune,Rahul,Sharma
1,102,Priya Patel,priya@techcorp.com,Mumbai,Priya,Patel
2,103,Amit Verma,amit@techcorp.com,Bangalore,Amit,Verma
3,104,Sneha Joshi,sneha@techcorp.com,Delhi,Sneha,Joshi
4,105,Rohan Singh,rohan@techcorp.com,Hyderabad,Rohan,Singh
5,106,Neha Gupta,neha@techcorp.com,Pune,Neha,Gupta
6,107,Akash Patel,akash@techcorp.com,Mumbai,Akash,Patel
7,108,Pooja Shah,pooja@techcorp.com,Pune,Pooja,Shah
8,109,Vikram Rao,vikram@techcorp.com,Chennai,Vikram,Rao
9,110,Divya Mehta,divya@techcorp.com,Ahmedabad,Divya,Mehta

FINAL DATASET

In [32]:
customer_df

   Customer_ID     Full_Name  Email       City First_Name Last_Name
0          101  Rahul Sharma  False       Pune      Rahul    Sharma
1          102   Priya Patel  False     Mumbai      Priya     Patel
2          103    Amit Verma  False  Bangalore       Amit     Verma
3          104   Sneha Joshi  False      Delhi      Sneha     Joshi
4          105   Rohan Singh  False  Hyderabad      Rohan     Singh
5          106    Neha Gupta  False       Pune       Neha     Gupta
6          107   Akash Patel  False     Mumbai      Akash     Patel
7          108    Pooja Shah  False       Pune      Pooja      Shah
8          109    Vikram Rao  False    Chennai     Vikram       Rao
9          110   Divya Mehta  False  Ahmedabad      Divya     Mehta