# DAY 28 ADVANCED PANDAS III

In [1]:
import pandas as pd
import numpy as np

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_4300\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" , encoding="latin1")
df.shape

(180519, 31)

In [3]:
df.columns

Index(['Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Department Name', 'Market',
       'Order Country', 'order date (DateOrders)', 'Order Id',
       'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Product Name', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [4]:
df[[
    "Order Id",
    "Market",
    "Customer Segment",
    "Category Name",
    "Sales",
    "Order Profit Per Order",
    "Order Item Quantity",
    "order date (DateOrders)"
]].head()

,Order Id,Market,Customer Segment,Category Name,Sales,Order Profit Per Order,Order Item Quantity,order date (DateOrders)
0,77202,Pacific Asia,Consumer,Sporting Goods,327.75,91.250000,1,1/31/2018 22:56
1,75939,Pacific Asia,Consumer,Sporting Goods,327.75,-249.089996,1,1/13/2018 12:27
2,75938,Pacific Asia,Consumer,Sporting Goods,327.75,-247.779999,1,1/13/2018 12:06
3,75937,Pacific Asia,Home Office,Sporting Goods,327.75,22.860001,1,1/13/2018 11:45
4,75936,Pacific Asia,Corporate,Sporting Goods,327.75,134.210007,1,1/13/2018 11:24

### MultiIndex + Advanced groupby() + transform()

In [14]:
market_segment = df.groupby(
     ["Market" , "Customer Segment"]
)["Sales"].sum()
market_segment

Market        Customer Segment
Africa        Consumer            1.187434e+06
              Corporate           6.997575e+05
              Home Office         4.072613e+05
Europe        Consumer            5.671565e+06
              Corporate           3.303071e+06
              Home Office         1.897761e+06
LATAM         Consumer            5.289639e+06
              Corporate           3.139115e+06
              Home Office         1.848859e+06
Pacific Asia  Consumer            4.286861e+06
              Corporate           2.515593e+06
              Home Office         1.471290e+06
USCA          Consumer            2.660291e+06
              Corporate           1.510871e+06
              Home Office         8.953663e+05
Name: Sales, dtype: float64

In [20]:
market_segment_df = market_segment.to_frame(
     name="Total_Sales"
)
market_segment_df

                                Total_Sales
Market       Customer Segment
Africa       Consumer          1.187434e+06
             Corporate         6.997575e+05
             Home Office       4.072613e+05
Europe       Consumer          5.671565e+06
             Corporate         3.303071e+06
             Home Office       1.897761e+06
LATAM        Consumer          5.289639e+06
             Corporate         3.139115e+06
             Home Office       1.848859e+06
Pacific Asia Consumer          4.286861e+06
             Corporate         2.515593e+06
             Home Office       1.471290e+06
USCA         Consumer          2.660291e+06
             Corporate         1.510871e+06
             Home Office       8.953663e+05

In [21]:
market_segment_df.index

MultiIndex([(      'Africa',    'Consumer'),
            (      'Africa',   'Corporate'),
            (      'Africa', 'Home Office'),
            (      'Europe',    'Consumer'),
            (      'Europe',   'Corporate'),
            (      'Europe', 'Home Office'),
            (       'LATAM',    'Consumer'),
            (       'LATAM',   'Corporate'),
            (       'LATAM', 'Home Office'),
            ('Pacific Asia',    'Consumer'),
            ('Pacific Asia',   'Corporate'),
            ('Pacific Asia', 'Home Office'),
            (        'USCA',    'Consumer'),
            (        'USCA',   'Corporate'),
            (        'USCA', 'Home Office')],
           names=['Market', 'Customer Segment'])

In [19]:
market_segment_df.loc[
    ("Pacific Asia", "Consumer")
]

Total_Sales    4.286861e+06
Name: (Pacific Asia, Consumer), dtype: float64

### transform()

In [ ]:
# calculate the total sales generated by its market.
df["Market_Total_Sales"] = df.groupby(
    "Market"
)["Sales"].transform("sum")

0         8.273744e+06
1         8.273744e+06
2         8.273744e+06
3         8.273744e+06
4         8.273744e+06
              ...
180514    8.273744e+06
180515    8.273744e+06
180516    8.273744e+06
180517    8.273744e+06
180518    8.273744e+06
Name: Market_Total_Sales, Length: 180519, dtype: float64

In [26]:
df[[
    "Market",
    "Sales",
    "Market_Total_Sales"
]].head(10)

         Market   Sales  Market_Total_Sales
0  Pacific Asia  327.75        8.273744e+06
1  Pacific Asia  327.75        8.273744e+06
2  Pacific Asia  327.75        8.273744e+06
3  Pacific Asia  327.75        8.273744e+06
4  Pacific Asia  327.75        8.273744e+06
5  Pacific Asia  327.75        8.273744e+06
6  Pacific Asia  327.75        8.273744e+06
7  Pacific Asia  327.75        8.273744e+06
8  Pacific Asia  327.75        8.273744e+06
9  Pacific Asia  327.75        8.273744e+06

In [27]:
# percentage contribution to its market:
df["Market_Sales_Contribution_%"] = (
    df["Sales"]
    .div(df["Market_Total_Sales"])
    .mul(100)
)

In [28]:
df[[
    "Market",
    "Sales",
    "Market_Total_Sales",
    "Market_Sales_Contribution_%"
]].head(10)

         Market   Sales  Market_Total_Sales  Market_Sales_Contribution_%
0  Pacific Asia  327.75        8.273744e+06                     0.003961
1  Pacific Asia  327.75        8.273744e+06                     0.003961
2  Pacific Asia  327.75        8.273744e+06                     0.003961
3  Pacific Asia  327.75        8.273744e+06                     0.003961
4  Pacific Asia  327.75        8.273744e+06                     0.003961
5  Pacific Asia  327.75        8.273744e+06                     0.003961
6  Pacific Asia  327.75        8.273744e+06                     0.003961
7  Pacific Asia  327.75        8.273744e+06                     0.003961
8  Pacific Asia  327.75        8.273744e+06                     0.003961
9  Pacific Asia  327.75        8.273744e+06                     0.003961

In [29]:
df.groupby("Market")["Sales"].sum()

Market
Africa          2.294453e+06
Europe          1.087240e+07
LATAM           1.027761e+07
Pacific Asia    8.273744e+06
USCA            5.066529e+06
Name: Sales, dtype: float64