# DAY 28 ADVANCED PANDAS III

In [1]:
import pandas as pd
import numpy as np

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_4300\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" , encoding="latin1")
df.shape

(180519, 31)

In [3]:
df.columns

Index(['Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Department Name', 'Market',
       'Order Country', 'order date (DateOrders)', 'Order Id',
       'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Product Name', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [4]:
df[[
    "Order Id",
    "Market",
    "Customer Segment",
    "Category Name",
    "Sales",
    "Order Profit Per Order",
    "Order Item Quantity",
    "order date (DateOrders)"
]].head()

,Order Id,Market,Customer Segment,Category Name,Sales,Order Profit Per Order,Order Item Quantity,order date (DateOrders)
0,77202,Pacific Asia,Consumer,Sporting Goods,327.75,91.250000,1,1/31/2018 22:56
1,75939,Pacific Asia,Consumer,Sporting Goods,327.75,-249.089996,1,1/13/2018 12:27
2,75938,Pacific Asia,Consumer,Sporting Goods,327.75,-247.779999,1,1/13/2018 12:06
3,75937,Pacific Asia,Home Office,Sporting Goods,327.75,22.860001,1,1/13/2018 11:45
4,75936,Pacific Asia,Corporate,Sporting Goods,327.75,134.210007,1,1/13/2018 11:24

### MultiIndex + Advanced groupby() + transform()

In [14]:
market_segment = df.groupby(
     ["Market" , "Customer Segment"]
)["Sales"].sum()
market_segment

Market        Customer Segment
Africa        Consumer            1.187434e+06
              Corporate           6.997575e+05
              Home Office         4.072613e+05
Europe        Consumer            5.671565e+06
              Corporate           3.303071e+06
              Home Office         1.897761e+06
LATAM         Consumer            5.289639e+06
              Corporate           3.139115e+06
              Home Office         1.848859e+06
Pacific Asia  Consumer            4.286861e+06
              Corporate           2.515593e+06
              Home Office         1.471290e+06
USCA          Consumer            2.660291e+06
              Corporate           1.510871e+06
              Home Office         8.953663e+05
Name: Sales, dtype: float64

In [20]:
market_segment_df = market_segment.to_frame(
     name="Total_Sales"
)
market_segment_df

                                Total_Sales
Market       Customer Segment
Africa       Consumer          1.187434e+06
             Corporate         6.997575e+05
             Home Office       4.072613e+05
Europe       Consumer          5.671565e+06
             Corporate         3.303071e+06
             Home Office       1.897761e+06
LATAM        Consumer          5.289639e+06
             Corporate         3.139115e+06
             Home Office       1.848859e+06
Pacific Asia Consumer          4.286861e+06
             Corporate         2.515593e+06
             Home Office       1.471290e+06
USCA         Consumer          2.660291e+06
             Corporate         1.510871e+06
             Home Office       8.953663e+05

In [21]:
market_segment_df.index

MultiIndex([(      'Africa',    'Consumer'),
            (      'Africa',   'Corporate'),
            (      'Africa', 'Home Office'),
            (      'Europe',    'Consumer'),
            (      'Europe',   'Corporate'),
            (      'Europe', 'Home Office'),
            (       'LATAM',    'Consumer'),
            (       'LATAM',   'Corporate'),
            (       'LATAM', 'Home Office'),
            ('Pacific Asia',    'Consumer'),
            ('Pacific Asia',   'Corporate'),
            ('Pacific Asia', 'Home Office'),
            (        'USCA',    'Consumer'),
            (        'USCA',   'Corporate'),
            (        'USCA', 'Home Office')],
           names=['Market', 'Customer Segment'])

In [19]:
market_segment_df.loc[
    ("Pacific Asia", "Consumer")
]

Total_Sales    4.286861e+06
Name: (Pacific Asia, Consumer), dtype: float64

### transform()

In [ ]:
# calculate the total sales generated by its market.
df["Market_Total_Sales"] = df.groupby(
    "Market"
)["Sales"].transform("sum")

0         8.273744e+06
1         8.273744e+06
2         8.273744e+06
3         8.273744e+06
4         8.273744e+06
              ...
180514    8.273744e+06
180515    8.273744e+06
180516    8.273744e+06
180517    8.273744e+06
180518    8.273744e+06
Name: Market_Total_Sales, Length: 180519, dtype: float64

In [26]:
df[[
    "Market",
    "Sales",
    "Market_Total_Sales"
]].head(10)

         Market   Sales  Market_Total_Sales
0  Pacific Asia  327.75        8.273744e+06
1  Pacific Asia  327.75        8.273744e+06
2  Pacific Asia  327.75        8.273744e+06
3  Pacific Asia  327.75        8.273744e+06
4  Pacific Asia  327.75        8.273744e+06
5  Pacific Asia  327.75        8.273744e+06
6  Pacific Asia  327.75        8.273744e+06
7  Pacific Asia  327.75        8.273744e+06
8  Pacific Asia  327.75        8.273744e+06
9  Pacific Asia  327.75        8.273744e+06

In [27]:
# percentage contribution to its market:
df["Market_Sales_Contribution_%"] = (
    df["Sales"]
    .div(df["Market_Total_Sales"])
    .mul(100)
)

In [28]:
df[[
    "Market",
    "Sales",
    "Market_Total_Sales",
    "Market_Sales_Contribution_%"
]].head(10)

         Market   Sales  Market_Total_Sales  Market_Sales_Contribution_%
0  Pacific Asia  327.75        8.273744e+06                     0.003961
1  Pacific Asia  327.75        8.273744e+06                     0.003961
2  Pacific Asia  327.75        8.273744e+06                     0.003961
3  Pacific Asia  327.75        8.273744e+06                     0.003961
4  Pacific Asia  327.75        8.273744e+06                     0.003961
5  Pacific Asia  327.75        8.273744e+06                     0.003961
6  Pacific Asia  327.75        8.273744e+06                     0.003961
7  Pacific Asia  327.75        8.273744e+06                     0.003961
8  Pacific Asia  327.75        8.273744e+06                     0.003961
9  Pacific Asia  327.75        8.273744e+06                     0.003961

In [29]:
df.groupby("Market")["Sales"].sum()

Market
Africa          2.294453e+06
Europe          1.087240e+07
LATAM           1.027761e+07
Pacific Asia    8.273744e+06
USCA            5.066529e+06
Name: Sales, dtype: float64

### Group Level Ranking

In [30]:
# top products within each market
product_market_sales = df.groupby(
     ["Market" , "Product Name"]
).agg(
     Total_Sales = ("Sales" , "sum")
).reset_index()
product_market_sales.head()

   Market                                   Product Name  Total_Sales
0  Africa                        Bag Boy Beverage Holder  1699.319977
1  Africa  Bridgestone e6 Straight Distance NFL Carolina  2911.089975
2  Africa  Bridgestone e6 Straight Distance NFL San Dieg  1887.409990
3  Africa  Bridgestone e6 Straight Distance NFL Tennesse  1759.449987
4  Africa                        Clicgear 8.0 Shoe Brush   629.369993

In [31]:
product_market_sales["Market_Product_Rank"] = (
    product_market_sales
    .groupby("Market")["Total_Sales"]
    .rank(
        method="dense",
        ascending=False
    )
)

In [32]:
product_market_sales.head(10)

,Market,Product Name,Total_Sales,Market_Product_Rank
0,Africa,Bag Boy Beverage Holder,1699.319977,39.0
1,Africa,Bridgestone e6 Straight Distance NFL Carolina,2911.089975,19.0
2,Africa,Bridgestone e6 Straight Distance NFL San Dieg,1887.409990,33.0
3,Africa,Bridgestone e6 Straight Distance NFL Tennesse,1759.449987,36.0
4,Africa,Clicgear 8.0 Shoe Brush,629.369993,54.0
5,Africa,Clicgear Rovic Cooler Bag,1919.520035,31.0
6,Africa,Columbia Men's PFG Anchor Tough T-Shirt,2250.000000,26.0
7,Africa,Diamondback Women's Serene Classic Comfort Bi,265182.329724,3.0
8,Africa,ENO Atlas Hammock Straps,2369.209989,23.0
9,Africa,Field & Stream Sportsman 16 Gun Fire Safe,473976.313035,1.0

In [33]:
top_products = product_market_sales[
     product_market_sales["Market_Product_Rank"] <= 3
]
top_products.sort_values(
     ["Market" , "Market_Product_Rank"]
).head(10)

,Market,Product Name,Total_Sales,Market_Product_Rank
9,Africa,Field & Stream Sportsman 16 Gun Fire Safe,4.739763e+05,1.0
29,Africa,Perfect Fitness Perfect Rip Deck,2.984503e+05,2.0
7,Africa,Diamondback Women's Serene Classic Comfort Bi,2.651823e+05,3.0
77,Europe,Field & Stream Sportsman 16 Gun Fire Safe,1.925904e+06,1.0
120,Europe,Perfect Fitness Perfect Rip Deck,1.218217e+06,2.0
74,Europe,Diamondback Women's Serene Classic Comfort Bi,1.137824e+06,3.0
177,LATAM,Field & Stream Sportsman 16 Gun Fire Safe,2.033498e+06,1.0
215,LATAM,Perfect Fitness Perfect Rip Deck,1.312641e+06,2.0
174,LATAM,Diamondback Women's Serene Classic Comfort Bi,1.259916e+06,3.0
265,Pacific Asia,Field & Stream Sportsman 16 Gun Fire Safe,1.469127e+06,1.0

### shift()

In [34]:
monthly_sales = df.groupby(
    [
        df["order date (DateOrders)"].str[:10],
        "Market"
    ]
)["Sales"].sum().reset_index()

monthly_sales.columns = [
    "Order_Date",
    "Market",
    "Total_Sales"
]

In [36]:
monthly_sales["Order_Date"] = pd.to_datetime(
    monthly_sales["Order_Date"] , format="mixed"
)

In [40]:
monthly_sales = monthly_sales.sort_values(
    ["Market", "Order_Date"]
)
monthly_sales.head(15)

     Order_Date  Market   Total_Sales  Previous_Sales
1391 2016-08-25  Africa   5063.240089             NaN
1397 2016-08-26  Africa  15786.150307     5063.240089
1402 2016-08-27  Africa   9159.100201    15786.150307
1408 2016-08-28  Africa  18256.120417     9159.100201
1414 2016-08-29  Africa  16127.320298    18256.120417
1419 2016-08-30  Africa  17010.030375    16127.320298
1425 2016-08-31  Africa  15338.480309    17010.030375
335  2016-09-01  Africa  14828.920298    15338.480309
340  2016-09-02  Africa  18530.740360    14828.920298
345  2016-09-03  Africa  17737.200369    18530.740360
351  2016-09-04  Africa  11845.670235    17737.200369
357  2016-09-05  Africa  12778.480293    11845.670235
363  2016-09-06  Africa  15341.880304    12778.480293
368  2016-09-07  Africa  14847.240280    15341.880304
374  2016-09-08  Africa  10305.890200    14847.240280

In [41]:
monthly_sales["Previous_Sales"] = (
    monthly_sales
    .groupby("Market")["Total_Sales"]
    .shift(1)
)
monthly_sales.head(15)

     Order_Date  Market   Total_Sales  Previous_Sales
1391 2016-08-25  Africa   5063.240089             NaN
1397 2016-08-26  Africa  15786.150307     5063.240089
1402 2016-08-27  Africa   9159.100201    15786.150307
1408 2016-08-28  Africa  18256.120417     9159.100201
1414 2016-08-29  Africa  16127.320298    18256.120417
1419 2016-08-30  Africa  17010.030375    16127.320298
1425 2016-08-31  Africa  15338.480309    17010.030375
335  2016-09-01  Africa  14828.920298    15338.480309
340  2016-09-02  Africa  18530.740360    14828.920298
345  2016-09-03  Africa  17737.200369    18530.740360
351  2016-09-04  Africa  11845.670235    17737.200369
357  2016-09-05  Africa  12778.480293    11845.670235
363  2016-09-06  Africa  15341.880304    12778.480293
368  2016-09-07  Africa  14847.240280    15341.880304
374  2016-09-08  Africa  10305.890200    14847.240280

In [42]:
daily_sales = monthly_sales.copy()

In [43]:
daily_sales.head()

     Order_Date  Market   Total_Sales  Previous_Sales
1391 2016-08-25  Africa   5063.240089             NaN
1397 2016-08-26  Africa  15786.150307     5063.240089
1402 2016-08-27  Africa   9159.100201    15786.150307
1408 2016-08-28  Africa  18256.120417     9159.100201
1414 2016-08-29  Africa  16127.320298    18256.120417

In [44]:
daily_sales = daily_sales.rename(columns={
    "Total_Sales": "Daily_Sales",
    "Previous_Sales": "Previous_Day_Sales"
})

In [45]:
daily_sales.head(10)

     Order_Date  Market   Daily_Sales  Previous_Day_Sales
1391 2016-08-25  Africa   5063.240089                 NaN
1397 2016-08-26  Africa  15786.150307         5063.240089
1402 2016-08-27  Africa   9159.100201        15786.150307
1408 2016-08-28  Africa  18256.120417         9159.100201
1414 2016-08-29  Africa  16127.320298        18256.120417
1419 2016-08-30  Africa  17010.030375        16127.320298
1425 2016-08-31  Africa  15338.480309        17010.030375
335  2016-09-01  Africa  14828.920298        15338.480309
340  2016-09-02  Africa  18530.740360        14828.920298
345  2016-09-03  Africa  17737.200369        18530.740360

### rolling() + Cumulative Calculations

## rolling()

In [46]:
daily_sales = daily_sales.sort_values(
    ["Market", "Order_Date"]
)

In [48]:
# Management wants a 3-day moving average of sales for each market.
daily_sales["3_Day_Moving_Avg"] = (
    daily_sales
    .groupby("Market")["Daily_Sales"]
    .transform(
        lambda x: x.rolling(3).mean()
    )
)

In [49]:
daily_sales[
    ["Order_Date", "Market", "Daily_Sales", "3_Day_Moving_Avg"]
].head(10)

     Order_Date  Market   Daily_Sales  3_Day_Moving_Avg
1391 2016-08-25  Africa   5063.240089               NaN
1397 2016-08-26  Africa  15786.150307               NaN
1402 2016-08-27  Africa   9159.100201      10002.830199
1408 2016-08-28  Africa  18256.120417      14400.456975
1414 2016-08-29  Africa  16127.320298      14514.180305
1419 2016-08-30  Africa  17010.030375      17131.157030
1425 2016-08-31  Africa  15338.480309      16158.610327
335  2016-09-01  Africa  14828.920298      15725.810327
340  2016-09-02  Africa  18530.740360      16232.713656
345  2016-09-03  Africa  17737.200369      17032.287009

##   Cumulative Sales

In [50]:
# Calculate cumulative sales within each market.
daily_sales["Cumulative_Sales"] = (
    daily_sales
    .groupby("Market")["Daily_Sales"]
    .cumsum()
)

In [51]:
daily_sales[
    [
        "Order_Date",
        "Market",
        "Daily_Sales",
        "Cumulative_Sales"
    ]
].head(10)

     Order_Date  Market   Daily_Sales  Cumulative_Sales
1391 2016-08-25  Africa   5063.240089       5063.240089
1397 2016-08-26  Africa  15786.150307      20849.390396
1402 2016-08-27  Africa   9159.100201      30008.490597
1408 2016-08-28  Africa  18256.120417      48264.611014
1414 2016-08-29  Africa  16127.320298      64391.931312
1419 2016-08-30  Africa  17010.030375      81401.961686
1425 2016-08-31  Africa  15338.480309      96740.441995
335  2016-09-01  Africa  14828.920298     111569.362293
340  2016-09-02  Africa  18530.740360     130100.102653
345  2016-09-03  Africa  17737.200369     147837.303022

## 3️⃣ Cumulative Maximum

In [52]:
daily_sales["Cumulative_Max_Sales"] = (
    daily_sales
    .groupby("Market")["Daily_Sales"]
    .cummax()
)

In [53]:
daily_sales[
    [
        "Order_Date",
        "Market",
        "Daily_Sales",
        "Cumulative_Sales",
        "Cumulative_Max_Sales"
    ]
].head(10)

     Order_Date  Market   Daily_Sales  Cumulative_Sales  Cumulative_Max_Sales
1391 2016-08-25  Africa   5063.240089       5063.240089           5063.240089
1397 2016-08-26  Africa  15786.150307      20849.390396          15786.150307
1402 2016-08-27  Africa   9159.100201      30008.490597          15786.150307
1408 2016-08-28  Africa  18256.120417      48264.611014          18256.120417
1414 2016-08-29  Africa  16127.320298      64391.931312          18256.120417
1419 2016-08-30  Africa  17010.030375      81401.961686          18256.120417
1425 2016-08-31  Africa  15338.480309      96740.441995          18256.120417
335  2016-09-01  Africa  14828.920298     111569.362293          18256.120417
340  2016-09-02  Africa  18530.740360     130100.102653          18530.740360
345  2016-09-03  Africa  17737.200369     147837.303022          18530.740360

In [54]:
daily_sales["Sales_Growth"] = (
    daily_sales["Daily_Sales"]
    - daily_sales["Previous_Day_Sales"]
)

In [55]:
daily_sales["Growth_Status"] = np.where(
    daily_sales["Sales_Growth"] > 0,
    "Increased",
    "Decreased"
)

In [56]:
daily_sales["Growth_Status"].value_counts()

Growth_Status
Increased    775
Decreased    757
Name: count, dtype: int64

In [57]:
daily_sales.loc[
    daily_sales["Sales_Growth"].idxmax(),
    [
        "Order_Date",
        "Market",
        "Daily_Sales",
        "Previous_Day_Sales",
        "Sales_Growth"
    ]
]

Order_Date            2017-10-26 00:00:00
Market                             Europe
Daily_Sales                  89785.200073
Previous_Day_Sales           24282.800415
Sales_Growth                 65502.399658
Name: 644, dtype: object