DATE AND TIME OPERATIONS IN PANDAS

In [2]:
import pandas as pd

In [3]:
sales_df = pd.DataFrame({
    "Order_ID":[101,102,103,104],
    "Customer":["Rahul","Priya","Amit","Sneha"],
    "Order_Date":[
        "2026-08-01",
        "2026-08-03",
        "2026-08-05",
        "2026-08-06"
    ],
    "Sales":[25000,18000,32000,21000]
})

sales_df

   Order_ID Customer  Order_Date  Sales
0       101    Rahul  2026-08-01  25000
1       102    Priya  2026-08-03  18000
2       103     Amit  2026-08-05  32000
3       104    Sneha  2026-08-06  21000

CORRECT DATA TYPE

In [6]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    4 non-null      int64
 1   Customer    4 non-null      object
 2   Order_Date  4 non-null      object
 3   Sales       4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

In [9]:
sales_df["Order_Date"] = pd.to_datetime(
     sales_df["Order_Date"]
)
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    4 non-null      int64
 1   Customer    4 non-null      object
 2   Order_Date  4 non-null      datetime64[ns]
 3   Sales       4 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 256.0+ bytes

EXTRACT YEAR , MONTH , DAY

In [10]:
sales_df["Year"] = sales_df["Order_Date"].dt.year
sales_df

   Order_ID Customer Order_Date  Sales  Year
0       101    Rahul 2026-08-01  25000  2026
1       102    Priya 2026-08-03  18000  2026
2       103     Amit 2026-08-05  32000  2026
3       104    Sneha 2026-08-06  21000  2026

In [11]:
sales_df["Month"] = sales_df["Order_Date"].dt.month
sales_df

   Order_ID Customer Order_Date  Sales  Year  Month
0       101    Rahul 2026-08-01  25000  2026      8
1       102    Priya 2026-08-03  18000  2026      8
2       103     Amit 2026-08-05  32000  2026      8
3       104    Sneha 2026-08-06  21000  2026      8

In [12]:
sales_df["Day"] = sales_df["Order_Date"].dt.day
sales_df

   Order_ID Customer Order_Date  Sales  Year  Month  Day
0       101    Rahul 2026-08-01  25000  2026      8    1
1       102    Priya 2026-08-03  18000  2026      8    3
2       103     Amit 2026-08-05  32000  2026      8    5
3       104    Sneha 2026-08-06  21000  2026      8    6

DAY NAME , MONTH NAME

In [ ]:
sales_df["Day_Name"] = sales_df["Order_Date"].dt.day_name()
sales_df

   Order_ID Customer Order_Date  Sales  Year  Month  Day   Day_Name
0       101    Rahul 2026-08-01  25000  2026      8    1   Saturday
1       102    Priya 2026-08-03  18000  2026      8    3     Monday
2       103     Amit 2026-08-05  32000  2026      8    5  Wednesday
3       104    Sneha 2026-08-06  21000  2026      8    6   Thursday

In [15]:
sales_df["Month_Name"] = sales_df["Order_Date"].dt.month_name()
sales_df

   Order_ID Customer Order_Date  Sales  Year  Month  Day   Day_Name Month_Name
0       101    Rahul 2026-08-01  25000  2026      8    1   Saturday     August
1       102    Priya 2026-08-03  18000  2026      8    3     Monday     August
2       103     Amit 2026-08-05  32000  2026      8    5  Wednesday     August
3       104    Sneha 2026-08-06  21000  2026      8    6   Thursday     August

DATE FILTERING

In [16]:
# Orders after August 3
sales_df[ sales_df["Order_Date"] > "2026-08-03"]

   Order_ID Customer Order_Date  Sales  Year  Month  Day   Day_Name Month_Name
2       103     Amit 2026-08-05  32000  2026      8    5  Wednesday     August
3       104    Sneha 2026-08-06  21000  2026      8    6   Thursday     August

In [17]:
# Orders in August
sales_df[
     sales_df["Month"] == 8
]

   Order_ID Customer Order_Date  Sales  Year  Month  Day   Day_Name Month_Name
0       101    Rahul 2026-08-01  25000  2026      8    1   Saturday     August
1       102    Priya 2026-08-03  18000  2026      8    3     Monday     August
2       103     Amit 2026-08-05  32000  2026      8    5  Wednesday     August
3       104    Sneha 2026-08-06  21000  2026      8    6   Thursday     August

In [18]:
# Orders from 2026
sales_df[
     sales_df["Year"] == 2026
]

   Order_ID Customer Order_Date  Sales  Year  Month  Day   Day_Name Month_Name
0       101    Rahul 2026-08-01  25000  2026      8    1   Saturday     August
1       102    Priya 2026-08-03  18000  2026      8    3     Monday     August
2       103     Amit 2026-08-05  32000  2026      8    5  Wednesday     August
3       104    Sneha 2026-08-06  21000  2026      8    6   Thursday     August

In [21]:
# Weekend Orders
sales_df[sales_df["Day_Name"].isin(
    [ "Saturday",
     "Sunday"]
)]

   Order_ID Customer Order_Date  Sales  Year  Month  Day  Day_Name Month_Name
0       101    Rahul 2026-08-01  25000  2026      8    1  Saturday     August

In [24]:
# Total sales in August
sales_df[
     sales_df["Month"] == 8
]["Sales"].sum()

96000

In [25]:
# Average sales
sales_df["Sales"].mean()

24000.0

In [26]:
# highest sales
sales_df["Sales"].max()

32000

In [27]:
# lowest sales
sales_df["Sales"].min()

18000

In [29]:
sales_df.sort_values(
     by = "Sales" ,
     ascending=False
)

   Order_ID Customer Order_Date  Sales  Year  Month  Day   Day_Name Month_Name
2       103     Amit 2026-08-05  32000  2026      8    5  Wednesday     August
0       101    Rahul 2026-08-01  25000  2026      8    1   Saturday     August
3       104    Sneha 2026-08-06  21000  2026      8    6   Thursday     August
1       102    Priya 2026-08-03  18000  2026      8    3     Monday     August