SORT_VALUES ()

In [45]:
import pandas as pd

In [46]:
employee_df = pd.read_csv("employee.csv")
employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

In [47]:
# SORT EMPLOYEES BY SALARY IN  ACSENDING ORDER
employee_df.sort_values(
     by=["Salary"]
     )

  Employee Department  Salary
0    Rahul      Sales   50000
3    Sneha    Finance   55000
1    Priya         HR   65000
2     Amit         IT   70000

In [48]:
# SORT EMPLOYEES BY SALARY IN  DESCENDING ORDER

employee_df.sort_values(
     by=["Salary"] ,
     ascending=False
     )

  Employee Department  Salary
2     Amit         IT   70000
1    Priya         HR   65000
3    Sneha    Finance   55000
0    Rahul      Sales   50000

In [49]:
# SORT EMPLOYEES BY EMPLOYEE NAME IN  ALPHABETICAL ORDER

employee_df.sort_values(
     by=["Employee"]
)

  Employee Department  Salary
2     Amit         IT   70000
1    Priya         HR   65000
0    Rahul      Sales   50000
3    Sneha    Finance   55000

In [50]:
employee_df.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
)

  Employee Department  Salary
3    Sneha    Finance   55000
1    Priya         HR   65000
2     Amit         IT   70000
0    Rahul      Sales   50000

SORT_INDEX ()

In [51]:
sorted_df = employee_df.sort_values(
     by=["Salary"] ,
     ascending = False
)

sorted_df

  Employee Department  Salary
2     Amit         IT   70000
1    Priya         HR   65000
3    Sneha    Finance   55000
0    Rahul      Sales   50000

In [52]:
sorted_df.sort_index()

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

RENAME ()

In [53]:
employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

In [54]:
updated_df = employee_df.rename(
     columns = {
          "Salary":"Monthly Salary"
     }
)

updated_df

  Employee Department  Monthly Salary
0    Rahul      Sales           50000
1    Priya         HR           65000
2     Amit         IT           70000
3    Sneha    Finance           55000

In [55]:
new_df = updated_df.rename(
     columns = {
          "Employee" : "Employee Name",
          "Department" : "Department Name"
     }
)

new_df

  Employee Name Department Name  Monthly Salary
0         Rahul           Sales           50000
1         Priya              HR           65000
2          Amit              IT           70000
3         Sneha         Finance           55000

In [56]:
employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

DROP ()

In [57]:
employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

In [63]:
new_df = employee_df.drop(
     columns = ["Department"]
)

new_df

  Employee  Salary
0    Rahul   50000
1    Priya   65000
2     Amit   70000
3    Sneha   55000

In [ ]:
new_df = employee_df.drop(
     columns = ["Department" , "Salary"]
)

new_df

  Employee
0    Rahul
1    Priya
2     Amit
3    Sneha

In [59]:
updated_df = new_df.drop(
     index = 1
)

updated_df

  Employee
0    Rahul
2     Amit
3    Sneha

In [60]:
employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

DROP_DUPLICATES ()

In [64]:
import pandas as pd

In [70]:
employee_data = {
     "Employee": ["Rahul", "Priya", "Rahul", "Amit", "Priya"],
    "Department": ["Sales", "HR", "Sales", "IT", "HR"],
    "Salary": [50000, 65000, 50000, 70000, 65000]
}

duplicate_df = pd.DataFrame(employee_data)

duplicate_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2    Rahul      Sales   50000
3     Amit         IT   70000
4    Priya         HR   65000

In [71]:
clean_df = duplicate_df.drop_duplicates()

clean_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
3     Amit         IT   70000

In [74]:

employee_unique = duplicate_df.drop_duplicates(
     subset = ["Employee"]
)

employee_unique

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
3     Amit         IT   70000