FILTERING AND ROW SELECTION

In [1]:
import pandas as pd

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_1484\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
employee_df = pd.read_csv("employee.csv")
employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

In [3]:
employee_df[employee_df["Salary"]>60000]

  Employee Department  Salary
1    Priya         HR   65000
2     Amit         IT   70000

In [4]:
employee_df[employee_df["Department"] == "IT"]

  Employee Department  Salary
2     Amit         IT   70000

In [5]:
employee_df[employee_df["Salary"]<60000]

  Employee Department  Salary
0    Rahul      Sales   50000
3    Sneha    Finance   55000

In [6]:
employee_df["Salary"]>60000

0    False
1     True
2     True
3    False
Name: Salary, dtype: bool

MULTIPLE CONDITION (AND & and OR |)

In [10]:
employee_df[
     (employee_df["Salary"]> 50000) &
     (employee_df["Department"] == "IT")
]

  Employee Department  Salary
2     Amit         IT   70000

In [11]:
employee_df[
     (employee_df["Salary"]<60000) &
     (employee_df["Department"]== "Finance") 
]

  Employee Department  Salary
3    Sneha    Finance   55000

In [12]:
employee_df[
     (employee_df["Department"] == "Sales") |
     (employee_df["Department"]== "HR") 
]

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000

In [14]:
employee_df[
     (employee_df["Salary"]>60000) |
     (employee_df["Department"]== "Finance") 
]

  Employee Department  Salary
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

ISIN()

In [15]:
employee_df[
     employee_df["Department"].isin(["IT" , "HR"])
]

  Employee Department  Salary
1    Priya         HR   65000
2     Amit         IT   70000

In [17]:
employee_df[
     employee_df["Department"].isin(["Sales" , "Finance"])
]

  Employee Department  Salary
0    Rahul      Sales   50000
3    Sneha    Finance   55000

In [19]:
employee_df[
     employee_df["Department"].isin(["IT" , "Sales" , "HR"])
]

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000

BETWEEN ()

In [7]:
import pandas as pd

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_12592\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [11]:
employee_df = pd.read_csv("employee.csv")
employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

In [25]:
employee_df[
     employee_df["Salary"].between(50000,65000)]

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
3    Sneha    Finance   55000

In [26]:
employee_df[
     employee_df["Salary"].between(55000,70000)
     ]

  Employee Department  Salary
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

In [27]:
employee_df[
     employee_df["Salary"].between(60000,70000)
]

  Employee Department  Salary
1    Priya         HR   65000
2     Amit         IT   70000

LOC ()

In [32]:
employee_df.loc[
     employee_df["Salary"] > 60000 ,
     ["Employee" , "Salary"]
]

  Employee  Salary
1    Priya   65000
2     Amit   70000

In [34]:
employee_df.loc[
     employee_df["Department"] == "HR",
     ["Employee" , "Department"]
]

  Employee Department
1    Priya         HR

In [38]:
employee_df.loc[
     employee_df["Department"].isin(["Sales","Finance"]) ,
     ["Employee" , "Salary"]
]

  Employee  Salary
0    Rahul   50000
3    Sneha   55000

In [42]:
employee_df.loc[
     : ,
     ["Employee" , "Salary"]
]

  Employee  Salary
0    Rahul   50000
1    Priya   65000
2     Amit   70000
3    Sneha   55000

ILOC ()

In [44]:
employee_df.iloc[0:2]

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000

In [46]:
employee_df.iloc[1:4]

  Employee Department  Salary
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

In [ ]:
employee_df.iloc[0:3 , 
                 [0,2]
               ]

  Employee  Salary
0    Rahul   50000
1    Priya   65000
2     Amit   70000

In [57]:
employee_df.iloc[: , [2]]

   Salary
0   50000
1   65000
2   70000
3   55000