MAP() , APPLY() , REPLACE() AND LAMBADA() FUNCTIONS

In [2]:
import pandas as pd

In [3]:
employee_df = pd.DataFrame({
     "Employee" :["Rahul" , "Priya" , "Amit" , "Sneha"],
     "Department" :["Sales" , "HR" , "IT" , "Finance"],
     "Salary" :[50000,65000,70000,55000]
})

employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

MAP()

In [7]:
# converting Department Names into Short Codes
employee_df["Department_Code"] = employee_df["Department"].map({
     "Sales" : "S",
     "HR" : "H",
     "IT" : "I",
     "Finance" : "F"
})

employee_df

  Employee Department  Salary Department_Code
0    Rahul      Sales   50000               S
1    Priya         HR   65000               H
2     Amit         IT   70000               I
3    Sneha    Finance   55000               F

In [8]:
# convert salary into grades
employee_df["Salary_Grades"] = employee_df["Salary"].map({
     50000 : "C",
     55000 : "C",
     65000 : "B",
     70000 : "A"
})

employee_df

  Employee Department  Salary Department_Code Salary_Grades
0    Rahul      Sales   50000               S             C
1    Priya         HR   65000               H             B
2     Amit         IT   70000               I             A
3    Sneha    Finance   55000               F             C

REPLACE()

In [ ]:
# replacing department name
employee_df["Department"].replace(
     "HR" ,
     "Human Resources"
)

0              Sales
1    Human Resources
2                 IT
3            Finance
Name: Department, dtype: object

In [12]:
# replacing multiple column names
employee_df["Department"].replace({
     "Sales" : "Sales Team",
     "IT" : "Information Technology"
})

0                Sales Team
1                        HR
2    Information Technology
3                   Finance
Name: Department, dtype: object

In [13]:
#replacing salary
employee_df["Salary"].replace(
     50000,52000
)

0    52000
1    65000
2    70000
3    55000
Name: Salary, dtype: int64

In [16]:
# replacing entire DataFrame
employee_df.replace({
     "Sales" : "Sales Team",
     70000 : 75000})

  Employee  Department  Salary Department_Code Salary_Grades
0    Rahul  Sales Team   50000               S             C
1    Priya          HR   65000               H             B
2     Amit          IT   75000               I             A
3    Sneha     Finance   55000               F             C

APPLY()

In [17]:
# increase every salary by 10 %
employee_df["Salary"].apply(
     lambda salary: salary * 1.10
)

0    55000.0
1    71500.0
2    77000.0
3    60500.0
Name: Salary, dtype: float64

In [18]:
# convert employee names to uppercase
employee_df["Employee"].apply(
     lambda name:name.upper()
)

0    RAHUL
1    PRIYA
2     AMIT
3    SNEHA
Name: Employee, dtype: object

In [20]:
# salary status
employee_df["Salary"].apply(
     lambda salary : "High"
     if salary >= 60000 else "Low"
)

0     Low
1    High
2    High
3     Low
Name: Salary, dtype: object

LAMBDA()

In [22]:
# increase salary by 20 %
employee_df["Salary"].apply(
     lambda salary : salary*1.20
)

0    60000.0
1    78000.0
2    84000.0
3    66000.0
Name: Salary, dtype: float64

In [23]:
# employee name length
employee_df["Employee"].apply(
     lambda name : len(name)
)

0    5
1    5
2    4
3    5
Name: Employee, dtype: int64

In [ ]:

employee_df  = pd.DataFrame({
     "Employee" : ["Rahul " , "Priya" , "Amit" , "Sneha"],
     "Salary" : [50000,65000,70000,55000],
     "Experience" : [2,5,4,1]
})
employee_df

  Employee  Salary  Experience
0   Rahul    50000           2
1    Priya   65000           5
2     Amit   70000           4
3    Sneha   55000           1

In [26]:
# Experience Bonus
employee_df["Bonus"] = employee_df["Experience"].apply(
     lambda bonus : bonus * 5000
)
employee_df

  Employee  Salary  Experience  Bonus
0   Rahul    50000           2  10000
1    Priya   65000           5  25000
2     Amit   70000           4  20000
3    Sneha   55000           1   5000